### ISSUE TITLE
some excetion with Bindings 

### ISSUE THREAD

**Issue by kelydia** [alejandroautalan/pygubu#102]
xxx.ui
Bindings: Sequence descriptor <Double-Button-1> Event Handler:onDBClick
xxx.py
	def onDBClick(event):
		print('aaa')
when i double click,get a exception like this:

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python36\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
TypeError: onDBClick() takes 1 positional argument but 2 were given
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python36\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
TypeError: onDBClick() takes 1 positional argument but 2 were given

**Comment by kelydia** [comment]
i resolved it
modify like this:
	def onDBClick(self,event):
		print('aaa')

**Comment by alejandroautalan** [comment]
Hello,
Yes, that is the correct solution. Check also https://github.com/alejandroautalan/pygubu/wiki/CommandProperties

Regards,
Alejandro A.
