### ISSUE TITLE
in my code how to update the attribute in the ui file defined

### ISSUE THREAD

**Issue by kelydia** [alejandroautalan/pygubu#107]
builder.add_from_file('login.ui')
        # 3: Set images path before creating any widget
        img_path = os.path.join(os.path.abspath(os.path.dirname(__file__)), '.', 'img')
        img_path = os.path.abspath(img_path)
        builder.add_resource_path(img_path)
        #4: Create the widget using a master as parent
        self.page = builder.get_object('root',self.root)
        img_label = builder.get_object('img',self.page)
        img_label.config(image=PhotoImage(file=img_path+'/1111.gif'))
MY question：I can't update the image of the img_label

**Comment by alejandroautalan** [comment]
Hello kelydia,

I think you're missing the reference to the image.
Taking the explanation from http://effbot.org/tkinterbook/label.htm

> You can use the label to display PhotoImage and BitmapImage objects. When doing this, **make sure you keep a reference to the image object**, to prevent it from being garbage collected by Python’s memory allocator.

You can try the following:

```python
    img_label = builder.get_object('img',self.page)
    img_label.new_image = PhotoImage(file=img_path+'/1111.gif')
    img_label.config(image=img_label.new_image)
```

**Comment by kelydia** [comment]
Solved my question！I am a novice, thank you for your patience 
：）
