### ISSUE TITLE
add Scrollbar for text

### ISSUE THREAD

**Issue by kelydia** [alejandroautalan/pygubu#108]
`   <child>
      <object class="tk.Frame" id="frame_left_top">
        <property name="background">#ffffff</property>
        <property name="height">260</property>
        <property name="width">380</property>
        <layout>
          <property name="column">0</property>
          <property name="padx">2</property>
          <property name="pady">2</property>
          <property name="propagate">False</property>
          <property name="row">0</property>
          <property name="sticky">nw</property>
        </layout>
        <child>
          <object class="tk.Text" id="text_msglist">
            <property name="height">260</property>
            <property name="width">380</property>
            <layout>
              <property name="column">0</property>
              <property name="propagate">False</property>
              <property name="row">0</property>
              <property name="sticky">nw</property>
            </layout>
          </object>
        </child>
        <child>
          <object class="ttk.Scrollbar" id="scrollbar">
            <property name="orient">vertical</property>
            <layout>
              <property name="column">1</property>
              <property name="propagate">True</property>
              <property name="row">0</property>
            </layout>
          </object>
        </child>
      </object>
    </child>`

code:
`        self.text_msglist = builder.get_object('text_msglist', self.frame_left_top)
        #config scrollbar
        T = self.text_msglist
        s = builder.get_object('scrollbar', self.frame_left_top)
        T.focus_set()
        s.config(command=T.yview)
        T.config(yscrollcommand=s.set)

**It does not work**

**Comment by alejandroautalan** [comment]
Hi, sorry for the late response.

You did not pass a complete example.  I made one and used your code.
This is working.  Let me know.

```xml
<?xml version='1.0' encoding='utf-8'?>
<interface>
  <object class="tk.Toplevel" id="Toplevel_1">
    <property name="height">200</property>
    <property name="width">200</property>
    <child>
      <object class="tk.Frame" id="frame_left_top">
        <property name="background">#ffffff</property>
        <property name="height">260</property>
        <property name="width">380</property>
        <layout>
          <property name="column">0</property>
          <property name="padx">2</property>
          <property name="pady">2</property>
          <property name="propagate">False</property>
          <property name="row">0</property>
          <property name="sticky">nw</property>
        </layout>
        <child>
          <object class="tk.Text" id="text_msglist">
            <property name="height">260</property>
            <property name="width">380</property>
            <layout>
              <property name="column">0</property>
              <property name="propagate">False</property>
              <property name="row">0</property>
              <property name="sticky">nw</property>
            </layout>
          </object>
        </child>
        <child>
          <object class="ttk.Scrollbar" id="scrollbar">
            <property name="orient">vertical</property>
            <layout>
              <property name="column">1</property>
              <property name="propagate">True</property>
              <property name="row">0</property>
            </layout>
          </object>
        </child>
      </object>
    </child>
  </object>
</interface>
```
```python
import tkinter
import pygubu


class Myapp:
    def __init__(self):
        builder = pygubu.Builder()
        builder.add_from_file('issue108.ui')
        self.mainwindow = builder.get_object('mainwindow')
        
        self.text_msglist = builder.get_object('text_msglist')
        #config scrollbar
        T = self.text_msglist
        s = builder.get_object('scrollbar')
        T.focus_set()
        s.config(command=T.yview)
        T.config(yscrollcommand=s.set)
        
    def run(self):
        self.mainwindow.mainloop()


if __name__ == '__main__':
    app = Myapp()
    app.run()

```

Regards
Alejandro A.

**Comment by kelydia** [comment]
It does not work properly
