### ISSUE TITLE
Title of the main window

### ISSUE THREAD

**Issue by termines** [alejandroautalan/pygubu#109]
Hi,
i want to set a title on the main window but it doesn't work !

here is the code i tried :

`

class MyApplication(pygubu.TkApplication):
    def _create_ui(self):
        self.builder = builder = pygubu.Builder()
        builder.add_from_file('test.ui')
        self.mainwindow = builder.get_object('Frame_1', self.master)
        self.toplevel = self.mainwindow.winfo_toplevel()
        self.toplevel.title("My title")

`
i also tried

`
self.toplevel.set_title("My title")
`

Please how to put a title on the main window ?

**Comment by alejandroautalan** [comment]
Hello temines, thanks for trying pygubu.

The TkApplication class already has a **set_title** method.
The correct way using this class is:

```python
class MyApplication(pygubu.TkApplication):
    def _create_ui(self):
        self.builder = builder = pygubu.Builder()
        builder.add_from_file('test.ui')
        self.mainwindow = builder.get_object('Frame_1', self.master)

        self.set_title("My title")


if __name__ == '__main__':
    root = tkinter.Tk()
    app = MyApplication(root)
    app.run()
```
The TkApplication is defined here https://github.com/alejandroautalan/pygubu/blob/master/pygubu/__init__.py
If you are using the class TkApplication, remember not to mix it with the Toplevel widget.
See this comment https://github.com/alejandroautalan/pygubu/issues/101#issuecomment-288712169

Best regards.
Alejandro A.

**Comment by termines** [comment]
Hello alejandroautalan,
Thank you for your quick answer :+1:  :)
Now it works !
