### ISSUE TITLE
Bug : Application still running in the task manager

### ISSUE THREAD

**Issue by termines** [alejandroautalan/pygubu#110]
Hello alejandroautalan,

(sorry for my english)
I find that when i make my app with pygubu using tk.LabelFrame or tk.Label and i build it with cxfreeze then when i run the app and i close it i noticed that the application still works in the task manager !!

Best Regards,
Termines.

**Comment by alejandroautalan** [comment]
Hi, 

> (sorry for my english)
I find that when i make my app with pygubu using tk.LabelFrame or tk.Label and i build it with cxfreeze then when i run the app and i close it i noticed that the application still works in the task manager !!

Maybe you are not closing the main window correctly. You need to destroy the main window.
See this page https://github.com/alejandroautalan/pygubu/wiki/CapturingDeleteWindowEvent for an example.

Regards.
Alejandro A.
