### ISSUE TITLE
Pygubu License change

### ISSUE THREAD

**Issue by alejandroautalan** [alejandroautalan/pygubu#111]
I have been requested to considere releasing pygubu under an Apache or MIT license so it could be used with projects with a BSD-3 clause.

Currently, the pygubu project has two main modules.

* The pygubu core, which consists of the Builder class, standard widgets, pygubu widgets and helpers.
* The interface editor (pygubudesigner)

What I would like to do is  relaunch the pygubu core with MIT license and keep the interface editor with a GPL-3 license.

**Comment by tritium21** [comment]
There are cases where GPLed libraries have added an explicit license to use the library *unmodified* with non-gpl-compliant code.  I believe some of the python freezer tools do this.

Any modifications to the library would poison the entire destination project, of course.

**Comment by tcareyintx** [comment]
If we go the route of the explicit license that would seem to preclude the ability to do a  bug fix without poisoning the project as you noted. How about custom widgets - would a new custom widget be considered modification of core in the current framework?

**Comment by tritium21** [comment]
Bug fixes can be done separate to the project that would be poisoned, and presuming PRs are pulled quickly, shouldn't be that big of a deal.  Custom widgets would depend entirely on how they are implemented - are they changes to the library code, or calls into its api?

I am not saying its the *best* or even a *preferable* option, but if you don't have copyright consignment as a term of contributing, it is the easiest to implement.

That said, MIT or Apache makes life a whole heck of a lot easier if you do have copyright consignment of contributions.

**Comment by tcareyintx** [comment]
Hey guys,

Did we make any decisions about this? Seems to me MIT would be the way to go for the core?

**Comment by alejandroautalan** [comment]
Hello everyone.
Sorry for the late reply.
I am currently quite busy in my daily work, but as soon as I have some free time, I will try to review the code and change the core to the new license (MIT).

Regards.
Alejandro A.

**Comment by oldmud0** [comment]
Hi @alejandroautalan, any ETA on this? I want to license one of my projects under the ISC license but am unable to do so until the core license is changed from GPLv3.
