### ISSUE TITLE
Always extra empty window opening

### ISSUE THREAD

**Issue by sausix** [alejandroautalan/pygubu#114]
Hi. I compared my python code and ui-file with the examples and can't find a difference.
There is always an empty extra window opening.

Code-Tags are messy. So files are attached.
Thank you.
![screenshot_20170619_031245](https://user-images.githubusercontent.com/21084645/27266088-25318656-549e-11e7-9974-4b72d1c20f37.png)

[minimal.ui.txt](https://github.com/alejandroautalan/pygubu/files/1083554/minimal.ui.txt)
[test-minimal.py.txt](https://github.com/alejandroautalan/pygubu/files/1083557/test-minimal.py.txt)

**Comment by alejandroautalan** [comment]
Hello sausix, thanks for trying pygubu.

You are using the tk.Toplevel widget so, calling tk.Tk() is not needed (the tk.Toplevel widget is already doing that).  See my comments in the modified example.

I created some usage pages for the tk.Toplevel widget  (but need improvement, sorry!)
https://github.com/alejandroautalan/pygubu/wiki/Using-the-tk.Toplevel-Widget
https://github.com/alejandroautalan/pygubu/wiki/TkApplication-vs-Tk.Toplevel

If you need more help, just let me know.

Best regards.
Alejandro A.

```python
#!/usr/bin/python
# File: test-minimal.py
import os

try:
    import tkinter as tk
    from tkinter import messagebox
except:
    import Tkinter as tk
    import tkMessageBox as messagebox

#import tkinter.ttk as ttk
import pygubu

CURRENT_DIR = os.path.abspath(os.path.dirname(__file__))

class MyApplication:
    def __init__(self):
        #1: Create a builder
        self.builder = builder = pygubu.Builder()

        #2: Load an ui file
        #builder.add_from_file('minimal.ui')
        builder.add_from_file(os.path.join(CURRENT_DIR, 'minimal.ui'))
        
        #3: Create the widget using self.master as parent
        self.mainwindow = builder.get_object('mainwindow')

    def quit(self, event=None):
        self.mainwindow.quit()

    def run(self):
        self.mainwindow.mainloop()
        
if __name__ == '__main__':
    # root = tk.Tk()   <-- Do not call tk.Tk(), the Toplevel widget does this.
    app = MyApplication()
    # root.mainloop()  <-- comment this
    app.run()     # <-- use the class method

```
