### ISSUE TITLE
sticky nsew

### ISSUE THREAD

**Issue by EhsanTadayon** [alejandroautalan/pygubu#117]
Hello
I'm trying to set sticky to "nsew" using the sticky panel. But once I save the file, the sticky values for "nsew" are not set. However, the other options work ( like "w" or "nw",... ) . 

I'm using the MacOs version of the app.

thanks.

**Comment by alejandroautalan** [comment]
Hi Ehsan thanks for trying pygubu.
> I'm trying to set sticky to "nsew" using the sticky panel. But once I save the file, the sticky values for "nsew" are not set. However, the other options work ( like "w" or "nw",... ) .

It happens in all widgets? What widgets are you using?  You can show me the pyguby and python versions?

Regards.
Alejandro A.

**Comment by EhsanTadayon** [comment]
Hi Alejadro, 
Thanks for the great app. 

I'm using pygubu version: 0.9.8.1 ( installed it through pip) and python 2.7.13(anaconda). I tested couple of widgets and containers and it sets NSEW for none of them. 

Best, 
Ehsan

**Comment by alejandroautalan** [comment]
Hello Ehsan.  I could not reproduce your issue.

Some questions:
* Are the sticky property values not saved to the ui file?
* Or, are the sticky values not set when the ui file is loaded from file?

Can you post a little example with the ui, python code, and expected behavior?

Regards.
Alejandro A.

**Comment by eugeniobaglieri** [comment]
same problem. Here a video: 
![pygubu](https://user-images.githubusercontent.com/1050414/75792527-64f84780-5d6e-11ea-94cf-cabbf116cd21.gif)

**Comment by alejandroautalan** [comment]
Hi Eugenio, thanks for trying pygubu.
You can set nsew by creating a selection with the mouse.

![output](https://user-images.githubusercontent.com/3482471/75796365-4dab6100-5d52-11ea-878f-87c4b45c003b.gif)

Regards,
Alejandro A.

**Comment by eugeniobaglieri** [comment]
Great!
Thank you.
