### ISSUE TITLE
pygubu-designer.exe does not appear to work

### ISSUE THREAD

**Issue by georgewicks56** [alejandroautalan/pygubu#118]
Hi,

I just just recently downloaded and installed pygubu from the tarball on my Windows 7 machine. I followed the procedure for installing pygubu "python setup.py install", which executed just fine.

I then ran pygubu-designer.exe, but after a second nothing happened. 

I have Python 3.6.1 installed, along with Anaconda and Tk (I tried "import tkinter" just to be sure, and that was fine).

What could I be missing? Is there any diagnostic steps that I should run?

Thanks,
George Wicks

**Comment by georgewicks56** [comment]
Ah, I think I figured it out: when I decided to manually run the Linux/UNIX script pygubu-designer, I got an error from Python: 

>>> from pygubudesigner import main
ERROR:pygubudesigner:I can't import module "appdirs". You need to have installed
 'appdirs' version 1.3 or higher. Hint, If your are using Debian, install packag
e python3-appdirs.

After I did the "pip install appdirs", I was then able to run the pygubu-designer.exe. Success!

Suggestions: you might want to list the package requirements, like appdirs, and also when you run the pygubu-designer.exe, catch the error and post it to the console.

I think that this could be a really good tool - Thanks!
George

**Comment by alejandroautalan** [comment]
Hello George, thanks for trying pygubu.

I created a new issue to apply your suggestions.
Thanks for the bug report.

Regards
Alejandro A.

**Comment by Baseamsatt** [comment]
The same exactly happen to me with the same window 7 and python  3.6 and there is no error , nothing happen at all and i pip install appdirs but the same problem resist

**Comment by alejandroautalan** [comment]
Hello @Baseamsatt thanks for trying pygubu and sorry for the late response.
Try to run pygubu-designer from the windows command:

    python3 -m pygubudesigner

And see if you have more errors or dependencies missing.

Regards
Alejandro A.

**Comment by DavidCreighton** [comment]
Hi, apologies Im new to Python programming. I installed Python 3.8 on my Win7 64bit system. TKinter works.
I cant open the Pygubu application,I ran  the setup file within the Pygubu-designer-master.zip file downloaded from Github. I also ran pip install via cmd direct. I cannot find the .exe file to execute the startup.
Further I have no clue what to do about XML... can you advise if I must download a file to execute. 

Perhaps advise if there is a demo tutorial on download and installation?
Thanx

**Comment by alejandroautalan** [comment]
Hello @DavidCreighton, thanks for trying pygubu.

> Hi, apologies Im new to Python programming. I installed Python 3.8 on my Win7 64bit system. TKinter works. I cant open the Pygubu application,I ran the setup file within the Pygubu-designer-master.zip file downloaded from Github. I also ran pip install via cmd direct. I cannot find the .exe file to execute the startup. Further I have no clue what to do about XML... can you advise if I must download a file to execute.
> 
> Perhaps advise if there is a demo tutorial on download and installation? Thanx

The recommended way to install on windows is using pip.

    pip3 install pygubu-designer

After "pip install pygubu-designer" the executable is installed in the "scripts" folder of your python installation. For exampe, if you have python installed in C:\Python38, pygubu-designer is installed in C:\Python38\Scripts\pygubu-designer.exe

Alternatively you can run the following command:

    python3 -m pygubudesigner

Regards
Alejandro A.

**Comment by DavidCreighton** [comment]
Merry Christmas and new year Alexandro.

Ive found the file in another saved location.  Thank you so much for
helping me.

PLease  may I ask, do you guys have a working DAW product. Im using LMMS
which the GUI looks and works great but the sound quality is produced poor?
[image: image.png]










Thanks Dave

0680734183
