### ISSUE TITLE
Crashes with non-number characters 

### ISSUE THREAD

**Issue by KMFSousa** [alejandroautalan/pygubu#120]
After accidentally typing a non-number character into a widget field (rowspan I believe it was) the designer simply crashes. This would probably be best handled by stripping fields which should only have numbers of non-number characters. Note it may require you to hit enter in that, or another field.

**Comment by alejandroautalan** [comment]
Hi Kristopher, thanks for trying pygubu.

I will fix the bug as soon as possible.

Regards
Alejandro A.
