### ISSUE TITLE
Error in startup script: wrong # args: should be "llength list"     while executing

### ISSUE THREAD

**Issue by yogeshcd** [alejandroautalan/pygubu#121]
I am using Linux Mint 18.2 Cinnamon 64-bit.
I downloaded PAGE from https://sourceforge.net/projects/page/
In terminal i executed 
$ ./configure
Configuring page

Using /usr/bin/wish8.6

#-------- Generated page --------------#
#!/bin/sh

PATH_TO_WISH=/usr/bin/wish8.6
PAGE_HOME=/home/name/Downloads/page

export PATH_TO_WISH
export PAGE_HOME

exec ${PATH_TO_WISH} ${PAGE_HOME}/page.tcl $*
#-------- End of page -----------------#

____________________________________________________________________________
After that i executed 
$ sh page
Error in startup script: wrong # args: should be "llength list"
    while executing
"llength[info commands tkTextInsert]"
    invoked from within
"if {![llength[info commands tkTextInsert]]} {
    ::tk::unsupported::ExposePrivateCommand tkTextInsert
}"
    (file "/home/yogesh/Downloads/page/page.tcl" line 37)

___________________________________________________________________________
It generate the above error.
But when I commented the 3 line of if condition in the file page.tcl (line no: 37,38,39) and typed $ sh page in terminal , the program executed without an error

**Comment by alejandroautalan** [comment]
Hi. I think you opened the issue on the wrong project.

Regards
Alejandro A.
