### ISSUE TITLE
running pygubu in ubuntu

### ISSUE THREAD

**Issue by ijash** [alejandroautalan/pygubu#122]
hi, i am trying to run pygubu.on the python3 console, i have no import error. and when i enter 
`pygubu-designer`
it returns an error:
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/code.py", line 91, in runcode
>     exec(code, self.locals)
>   File "<input>", line 1, in <module>
> 
> NameError: name 'designer' is not defined
I am using ubuntu as my OS.

**Comment by alejandroautalan** [comment]
Hello Jastria, thanks for trying pygubu.

What version of ubuntu are you using?
What method did you use to install pygubu?
Did you install it as superuser or common user?

Regards.
Alejandro A.

**Comment by ijash** [comment]
it's ubuntu 17.04
i am using normal user. just like your instruction on readme.

oh, btw i install it using pip3 , not pip3.5. is it okay?

**Comment by rickardcronholm** [comment]
Any updates on this? I am also using Ubuntu 17.04. Installed using pip (not pip3x mind you). No error during import, but I don't even have a pygubu* binary

**Comment by alejandroautalan** [comment]
Hello rickardcronholm thanks for trying pygubu.  Sorry for the late response.

> Any updates on this? I am also using Ubuntu 17.04. Installed using pip (not pip3x mind you). No error during import, but I don't even have a pygubu* binary

I was able to test with ubuntu17.04
Installing pygubu with pip as a **normal user**, the pygubu-designer script is located at

    $HOME/.local/bin

So you can add that path to your environment variables, or run pygubu-designer by typing this command in the console:

    ./.local/bin/pygubu-designer

About the error mentioned by ijash, I could not reproduce it. Does it still happen?

Regards
Alejandro A.

**Comment by rickardcronholm** [comment]
Thanks for the hint. I just assumed that was already added to my path :)

I am not able to reproduce the original issue ijash mentioned.
