### ISSUE TITLE
Enable continuous integration with Travis

### ISSUE THREAD

**Issue by scls19fr** [alejandroautalan/pygubu#129]
Hello,

You might enable [continuous integration](https://en.wikipedia.org/wiki/Continuous_integration) with [Travis](https://travis-ci.org/)

Kind regards

**Comment by alejandroautalan** [comment]
Hi, scls19fr.
Thanks for trying pygubu and for the suggestion.  I will read the documentation and implement it soon.

Regards
Alejandro A.
