### ISSUE TITLE
Creating a standalone python gile

### ISSUE THREAD

**Issue by Cediddi** [alejandroautalan/pygubu#130]
Hi, great software. I really dislike using tkinter because of it's lack of tooling but this is awesome. Only thing I miss from Qt bindings is a way to compile importable py file. I prefer not importing pygubu from my software (a plugin for thonny). Is there a way to do this, like in pyuic ?

Pyuic is a console application that turns Qt's .ui files into importable py files.

**Comment by alejandroautalan** [comment]
Hello cediddi, thanks for trying pygubu.

In the **develop** branch there is a first attempt to do something like you mention.
It's a script that converts a ui file into python instructions. It is named **ui2code.py** inside the pygubu folder.

```
ui2code.py -h 
usage: ui2code.py [-h] filename [rootwidget]

positional arguments:
  filename    .ui file
  rootwidget  Toplevel widget (default: mainwidow)

optional arguments:
  -h, --help  show this help message and exit
```

Its a very basic script that for now it only works ok with ui files using the standard widgets (not pygubu widgets or helpers).
Later I can investigate pyuic from Qt and improve the script.

Let me know if this helps you.

Regards
Alejandro A.

**Comment by CarterSnich** [comment]
Where should I see the py file?

**Comment by olin000** [comment]
@CarterSnich  ...\Python37_64\Lib\site-packages\pygubu\

**Comment by alejandroautalan** [comment]
Fixed. Added new way to generate code.
