### ISSUE TITLE
Add ability to use the place and pack layout managers

### ISSUE THREAD

**Issue by programmingkidx** [alejandroautalan/pygubu#135]
The grid layout manager is just one of the layout managers available to Tkinter users. Pygubu can be improved by adding support for the place and pack layout managers. Making an interface using the place layout manager is very easy.  I would say easier than using the grid layout manager. Giving the user the operation of which layout manager to use can be very beneficial to everyone.

**Comment by alejandroautalan** [comment]
Fixed on last version (9752bfb05032ed879ab498d30d4ce1fe03326279)
