### ISSUE TITLE
How to put a picture into a frame?

### ISSUE THREAD

**Issue by awindhorn** [alejandroautalan/pygubu#137]
I am trying to display a graph inside of a Tkinter frame.  Any hints how to do that?  It is a .png file-like object.  It will be changed frequently during use.  Thanks.

Regards,
Allen

**Comment by insolor** [comment]
Use tk.Canvas. Also probably you will need Pillow (pil) to load png file.

**Comment by awindhorn** [comment]
OK, thanks.  Now I've got a canvas in my UI object, along with a button to put a picture in one of them.  The button is bound to a method "on_btnplot1_clicked(self)" with pseudocode:

    def on_btnplot1_clicked(self):
        im = Image.open('CarterCoeffGray.png') 
        plt1 = self.mainwindow['canPlot1'] # or something??
        imgPlt1 = plt1.create_image(0, 0, anchor=NW))
        plt1.image = 'Plot1.png' # ...or im or what?
        
I don't know how to reference the canvas inside the method (same problem for entry box etc.).  And I don't know how to put the image inside the canvas.  By the way, I want the image to fill the canvas in at least one dimension.

Any further advice?  Thanks.

Regards,
Allen

**Comment by laiqun** [comment]
Label have a property named Image ,you can use this.

**Comment by NateJose123** [comment]
I've tried to use the image property but it doesn't allow me to import jpeg, png or heic filetypes. Any suggestions on how to deal with this?

Thanks,

Nathan Jose.

**Comment by alejandroautalan** [comment]
Hi Nathan, thanks for trying pygubu and sorry for the late response.

Image format support will depend on your Tk version installed.
Tk versions bellow 8.6 only support '.gif', '.pgm' and '.ppm'
Tk version 8.6 adds support to '.png' format.

For other image formats you need to use Pillow module.

Starting from pygubu version 0.9.8.4 now you can load other image formats
if Pillow (or PIL) is installed.

Tryit and let me know.

Regards.
Alejandro A.

**Comment by rasti1030** [comment]
hey every one.........any pne tell me  that how  i import a jpg image in tkinter .........

**Comment by rasti1030** [comment]
hey ......anyone tell me about that how to inter .jpg image on tkinter canvas........

**Comment by alejandroautalan** [comment]
> hey ......anyone tell me about that how to inter .jpg image on tkinter canvas........

Hi, thanks for trying pygubu.
For .jpg images you need to install Pillow library.
I made a simple example here: https://github.com/alejandroautalan/pygubu-designer/tree/master/examples/jpg_image_on_canvas

Regards.
Alejandro A.
