### ISSUE TITLE
NSException : pygubu crashes on OSX within a minute after load with uncaught exception

### ISSUE THREAD

**Issue by faheem-hasan** [alejandroautalan/pygubu#142]
I tried this on multiple computers (MAC OSX SIerra & MAC OSX High Sierra).

@alejandroautalan Please Help if you think there's a solution for this. I really like the concept of this library and would love to get it working so I can start using it to build something. 

2018-03-28 12:49:36.916 Python[1157:178979] *** Assertion failure in -[_NSCGSWindow setFrame:], /Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1504.83.101/CGS.subproj/NSCGSWindow.m:663
2018-03-28 12:49:36.923 Python[1157:178979] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: CGRectContainsRect(CGRectMake((CGFloat)INT_MIN, (CGFloat)INT_MIN, (CGFloat)INT_MAX - (CGFloat)INT_MIN, (CGFloat)INT_MAX - (CGFloat)INT_MIN), frame)'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fffb92b62cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffce0cd48d objc_exception_throw + 48
	2   CoreFoundation                      0x00007fffb92bb042 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fffbad03be0 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   AppKit                              0x00007fffb6e4a485 -[_NSCGSWindow setFrame:] + 252
	5   AppKit                              0x00007fffb6ec75a0 _NXCreateWindowWithStyleMask + 157
	6   AppKit                              0x00007fffb6ec741e _NSCreateWindow + 184
	7   AppKit                              0x00007fffb6f11270 -[NSWindow _commonAwake] + 1465
	8   AppKit                              0x00007fffb75c5b96 -[NSWindow _resolveAutomaticEnterFullScreenFlags] + 51
	9   AppKit                              0x00007fffb6f10b5b -[NSWindow makeKeyAndOrderFront:] + 31
	10  Tk                                  0x000000010367eaa3 XMapWindow + 164
	11  Tk                                  0x00000001035f02b9 Tk_MapWindow + 178
	12  Tk                                  0x00000001035f89e1 TkInstallFrameMenu + 271
	13  Tcl                                 0x000000010356b097 TclServiceIdle + 77
	14  Tcl                                 0x0000000103551c59 Tcl_DoOneEvent + 350
	15  _tkinter.cpython-36m-darwin.so      0x00000001027dbaa1 _tkinter_tkapp_mainloop + 209
	16  Python                              0x000000010006a4c8 _PyCFunction_FastCallDict + 552
	17  Python                              0x00000001000f3e94 call_function + 612
	18  Python                              0x00000001000f58a4 _PyEval_EvalFrameDefault + 5604
	19  Python                              0x00000001000f3230 _PyEval_EvalCodeWithName + 2720
	20  Python                              0x00000001000f3a5b fast_function + 219
	21  Python                              0x00000001000f3e7b call_function + 587
	22  Python                              0x00000001000f58a4 _PyEval_EvalFrameDefault + 5604
	23  Python                              0x00000001000f3bde fast_function + 606
	24  Python                              0x00000001000f3e7b call_function + 587
	25  Python                              0x00000001000f58a4 _PyEval_EvalFrameDefault + 5604
	26  Python                              0x00000001000f3bde fast_function + 606
	27  Python                              0x00000001000f3e7b call_function + 587
	28  Python                              0x00000001000f58a4 _PyEval_EvalFrameDefault + 5604
	29  Python                              0x00000001000f3230 _PyEval_EvalCodeWithName + 2720
	30  Python                              0x00000001000f33d4 PyEval_EvalCode + 100
	31  Python                              0x000000010012ff7e PyRun_FileExFlags + 206
	32  Python                              0x000000010013021f PyRun_SimpleFileExFlags + 447
	33  Python                              0x000000010014986a Py_Main + 3914
	34  Python                              0x0000000100000dfe Python + 3582
	35  Python                              0x0000000100000c34 Python + 3124
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by lisandromc** [comment]
Be aware that the Python package supplied by Apple with macOS 10.6+ (at least using Homebrew) uses an old an buggy version of Tk/Tcl that causes crashes.

> If you are using macOS 10.6 or later, the Apple-supplied Tcl/Tk 8.5 has serious bugs that can cause application crashes. If you wish to use IDLE or Tkinter, do not use the Apple-supplied Pythons. Instead, install and use a newer version of Python from python.org or a third-party distributor that supplies or links with a newer version of Tcl/Tk.

While your particular error is not the same as mine, it's still likely that downloading and installing Python 3.6+ from the Python website fixes the issue.
https://www.python.org/downloads/mac-osx/

**Comment by lisandromc** [comment]
Be aware that the Python package supplied by Apple with macOS 10.6+ (at least using Homebrew) uses an old an buggy version of Tk/Tcl that causes crashes.

> If you are using macOS 10.6 or later, the Apple-supplied Tcl/Tk 8.5 has serious bugs that can cause application crashes. If you wish to use IDLE or Tkinter, do not use the Apple-supplied Pythons. Instead, install and use a newer version of Python from python.org or a third-party distributor that supplies or links with a newer version of Tcl/Tk.

While your particular error is not the same as mine, it's still likely that downloading and installing Python 3.6+ from the Python website fixes the issue.
https://www.python.org/downloads/mac-osx/
