### ISSUE TITLE
New Logo for pygubu

### ISSUE THREAD

**Issue by TKaluza** [alejandroautalan/pygubu#143]
## New pygubu logo
This is just an idea to give this nice programm a new logo. I can make a icon of it, if you like it or change something. Just as an idea. 

I used the python logo from wikipedia
https://commons.wikimedia.org/wiki/File:Python-logo-notext.svg

and a tcl tk logo from this page:
http://ateliers.mse.free.fr/tkinter/page_tkinter.html

and used to rebuild a glade logo picture. 

![pygubulogo](https://user-images.githubusercontent.com/17787801/38465567-9b645f4a-3b1d-11e8-8887-74bf02a932d7.png)

**Comment by alejandroautalan** [comment]
Hi Tkluza, thanks for trying pygubu and for making this logo!
I really like the design. A change that I would like to see is the text "pygubu" all in lowercase. Also, If you can make an icon it would be great.

Thank you for your work!. Regards.
Alejandro A.

**Comment by TKaluza** [comment]
Heythere! 
I'm sorry for the long delay! 
Of course I can do that! If you want anything else changed, please just say it. 
Or if you have preferred font just let me now.
The font used was Open Sans Condensed

But I would suggest ubuntu mono. it looks nicer in lowercase letters. This would be my final, if you do have any other wishes. 

Optional I can make the background white (picture on the bottom) or semitransparent. But it looks good in my opinion this way (first picture):
![image](https://user-images.githubusercontent.com/17787801/39667330-c431e388-50b3-11e8-935e-5ee6bbaee039.png)

![image](https://user-images.githubusercontent.com/17787801/39667355-267625f4-50b4-11e8-91b7-f19037eec2ea.png)

**Comment by TKaluza** [comment]
Picture Family suggestion 1 for icon:
![image](https://user-images.githubusercontent.com/17787801/39667422-2910f634-50b6-11e8-8ac6-e92f4ff8cbdf.png)

**Comment by TKaluza** [comment]
So the icon file is ready. Can I maybe "push" it with github to the project ^^ (would be great!) otherwise I can just attach it

**Comment by TKaluza** [comment]
No problem! 
If you need more graphics just say so ^^, I like to try. 
I'm sorry for extra work but I really appreciate doing my first github pulling :smiley_cat:
