### ISSUE TITLE
SyntaxError: encoding problem: utf8

### ISSUE THREAD

**Issue by retsyo** [alejandroautalan/pygubu#150]
I think you mean utf-8 in all the py file
I am using python 3.6 on windows

**Comment by retsyo** [comment]
```bash
>e:\prg\py\Anaconda3_64\python.exe -u "pygubu-designer.py"
  File "pygubu-designer.py", line 2
SyntaxError: encoding problem: utf8
```

**Comment by retsyo** [comment]
btw, I just copy and rename pygubu-master\bin\pygubu-designer to pygubu-master\pygubu-designer.py

**Comment by bitstep-btc** [comment]
I'm getting the following message as the application terminates unexpectedly.

Traceback (most recent call last):
  File "/usr/local/bin/pygubu-designer", line 11, in <module>
    sys.exit(start_pygubu())
  File "/usr/local/lib/python3.6/site-packages/pygubudesigner/main.py", line 558, in start_pygubu
    app.run()
  File "/usr/local/lib/python3.6/site-packages/pygubu/__init__.py", line 44, in run
    self.toplevel.mainloop()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 1280, in mainloop
    self.tk.mainloop(n)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

Are there any suggetions how to fix this ?

**Comment by Llorc** [comment]
On my side, the problem was the path was using "\".
Backslash is an escape character in Python string literals. 
By using raw string literal you can disable escaping behavior. 
Simply put an 'r' char before the string, like INSTALLED_BASE_DIR=r"C:\blabla"

**Comment by lisandromc** [comment]
This error happens with macOS 10.6+ when using the Python package supplied by Apple (at least using Homebrew), because it still uses an old an buggy version of Tk.

> If you are using macOS 10.6 or later, the Apple-supplied Tcl/Tk 8.5 has serious bugs that can cause application crashes. If you wish to use IDLE or Tkinter, do not use the Apple-supplied Pythons. Instead, install and use a newer version of Python from python.org or a third-party distributor that supplies or links with a newer version of Tcl/Tk.

Downloading and installing Python 3.6+ from the Python website fixes the issue.
https://www.python.org/downloads/mac-osx/
