### ISSUE TITLE
Apply limitation for selecting the checkboxes in Python

### ISSUE THREAD

**Issue by ZaRaSm** [alejandroautalan/pygubu#151]
Hello,
I want to apply limitation for check boxes.The user just can select 2 checkboxes and when more than 2 check boxes are selected , the rest of checkboxes become disabled till the user deselect one of the checked checkboxes ! The problem is when I select 2 checkboxes just the last on is disabled ! 

this is my code :

`from tkinter import *

class CheckBar(Frame):
    def __init__(self, parent=None, picks=[], side=TOP, anchor=W):
        Frame.__init__(self, parent)
        self.vars = []
        for pick in picks:
            var = IntVar()

            def cbcheck():
                if list(Prm.lable()).count(1) > 1:
                    chk.config(state=DISABLED)
                else:
                    chk.config(state=NORMAL)

            chk = Checkbutton(self, text=pick, variable=var, command=cbcheck)
            chk.pack(side=side, anchor=anchor, expand=YES)
            self.vars.append(var)

    def lable(self):
        return map((lambda var: var.get()), self.vars)

if __name__ == '__main__':
    root = Tk()
    root.title("Graph")
    root.geometry("300x300")
    lfckb = LabelFrame(root, text="Select Parameters : ", relief=GROOVE)
    lfckb.pack(padx=10, pady=10, side=LEFT)
    Prm = CheckBar(lfckb,['A','B','C','D','E'])
    Prm.pack(side=LEFT, fill=X)
Button(root, text='Cancel', relief=RAISED, bd=3, command=root.quit).pack(side=RIGHT)
root.mainloop()

<img width="232" alt="pic" src="https://user-images.githubusercontent.com/33186024/42134954-b4d42c1c-7d44-11e8-9731-5b075c8ab337.png">
`

**Comment by alejandroautalan** [comment]
Hello ZaRaSm, thanks for trying pygubu.

> I want to apply limitation for check boxes.The user just can select 2 checkboxes and when more than 2 check boxes are selected , the rest of checkboxes become disabled till the user deselect one of the checked checkboxes ! The problem is when I select 2 checkboxes just the last on is disabled !

I know it's not a specific question about pygubu but I'll try anyway.
How about the following approach? Let me know.

```python
from tkinter import *


class CheckBar2(Frame):
    def __init__(self, parent, picks=[], slimit=2):
        Frame.__init__(self, parent)
        self.vars = []
        self.slimit = slimit  #  max selected items allowed
        self.selcount = 0  # current selected items count
        
        # Create checkbuttons
        for pick in picks:
            var = IntVar()
            chk = Checkbutton(self, text=pick, variable=var, command=self.on_cbclicked)
            
            # define button command
            def cbhandler(self=self, btn=chk, var=var):
                self.on_cbclicked(btn, var)
            
            # configure callback
            chk.configure(command=cbhandler)
            chk.pack(side=TOP, anchor=W, expand=YES)
            self.vars.append(var)
    
    def on_cbclicked(self, btn, var):
        prevcount = self.selcount
        
        value = var.get()
        if value == 1:
            self.selcount += 1
        else:
            self.selcount -= 1
        
        process = False
        state = NORMAL
        if self.selcount == self.slimit:
            # disable all other
            process = True
            state = DISABLED
        elif (self.selcount < self.slimit) and (prevcount == self.slimit):
            # enable all
            process = True
            state = NORMAL
        if process:
            for n in self.winfo_children():
                w = self.nametowidget(n)
                value = int(w.getvar(w.cget('variable')))
                if value == 0:
                    w.configure(state=state)

if __name__ == '__main__':
    root = Tk()
    root.title("Graph")
    root.geometry("300x300")
    lfckb = LabelFrame(root, text="Select Parameters (max 3): ", relief=GROOVE)
    lfckb.pack(padx=10, pady=10, side=LEFT)
    
    Prm2 = CheckBar2(lfckb, picks=['F','G','H','I','J'], slimit=3)
    Prm2.pack(side=LEFT, fill=X)    
    
    Button(root, text='Cancel', relief=RAISED, bd=3, command=root.quit).pack(side=RIGHT)
    root.mainloop()
```

Regards
Alejandro A.

**Comment by ZaRaSm** [comment]
Hello,
This is exactly what I wanted . Thank you very much ! :)
