### ISSUE TITLE
How to get all widgets and their data variables?

### ISSUE THREAD

**Issue by native-api** [alejandroautalan/pygubu#164]
The advertized method for using the module, `Builder.get_object("name")` creates the entire GUI but only returns one widget.

This GUI is unusable. To be able to use it, I need to get all the widgets and their data variables and the corresponding names as defined in the `.ui`, to be able to assign them to attributes of the GUI class instance. How is this supposed to be done?

**Comment by alejandroautalan** [comment]
Hello native-api, thanks for trying pygubu and sorry for the late response.

> The advertized method for using the module, Builder.get_object("name") creates the entire GUI but only returns one widget.

Yes, the main idea here is to separate the code of building
the GUI and the code of your program logic.

Supose that we have an UI like this:

```
Frame: mainframe
  Frame: framelogo
    image: imglogo
  Frame:
    entry: username
      variable: varuser
    entry: password
      variable: varpwd
    button: btn_login

```
You must create the entire GUI calling get_object on the root widget (in this case 'mainframe').
Once you have done that, you can access all descendant widgets of mainframe
that you have interest.

```python
class app:
    def __init__(self):
        mainframe = builder.get_object('mainframe')
        self.user = builder.get_object('username')
        self.pass = builder.get_object('password')

```

> This GUI is unusable. To be able to use it, I need to get all the widgets and their data variables and the corresponding names as defined in the .ui, to be able to assign them to attributes of the GUI class instance. How is this supposed to be done?

I you have defined variables for widgets that support them, then you can get all associated
variables at once.
For example, import all variables in my app class:

```python
class app:
    def __init__(self):
        ...
        mainframe = builder.get_object('mainframe')
        ...
        builder.import_variables(self)
        ...
        # access imported variables in self
        self.varuser.set('defaultuser')

```

I hope that this resolves your issues.

Regards,
Alejandro A.
