### ISSUE TITLE
Not all widgets support state property

### ISSUE THREAD

**Issue by ramwoolf** [alejandroautalan/pygubu#168]
I would like to use a state property for PathChooserInput, Frame and LabelFrame widgets, but it isn't defined there. I can't disable a group of widgets where are few path choosers

**Comment by alejandroautalan** [comment]
Hello, and thanks for trying pygubu.

Tk widgets Frame and LabelFrame don't have state option.
You will need to subclass Frame and add that functionality.
Alternatively, you can iterate the children and set the state.
Example

```python
    # ...
    newstate = 'disabled'
    objects = self.builder.get_object('mainframe').winfo_children()
    for w in objects:
        try:
            w.config(state=newstate)
        except Exception as e:
            # do something or
            pass
```
