### ISSUE TITLE
Treeview delete nodes

### ISSUE THREAD

**Issue by jpmpdias** [alejandroautalan/pygubu#174]
Hi Alejandro,

I'm using a treeview command and I'm having trouble deleting the existing nodes and adding new ones. If I use the delete command, the nodes disappear, but when I load new data to the tree, the old nodes reappear and the the new nodes are added at the end of the tree.

What am I doing wrong?

Thanks
Joao

**Comment by alejandroautalan** [comment]
Hello Joao, thanks for trying pygubu.
Could you pass an example of reduced code showing the problem? That way I can help you better.
Meanwhile I show you a small example of using treeview and pygubu.

Regards
Alejandro A.

file: main.py

```python
from pathlib import Path
import random
import pygubu

APP_DIR = Path(__file__).resolve().parent

class MyApp:
	def __init__(self):
		self.builder = builder = pygubu.Builder()
		uifile = APP_DIR.joinpath('main.ui')
		builder.add_from_file(uifile)
		self.mainwindow = builder.get_object('mainwindow')
		self.tree = builder.get_object('mytree')
		builder.connect_callbacks(self)
		
	def on_populate_action(self):
		'''Add some items to the treeview.'''
		
		count = random.randint(10, 20)
		for k in range(count):
			num = random.randint(100, 5000)
			username = f'User_{num}'
			score = random.randint(0, 1000)
			self.tree.insert('', 'end', values=(username, score))
		
	def on_clear_action(self):
		'''Remove all items from treeview.'''
		
		children = self.tree.get_children()
		self.tree.delete(*children)
		
	def run(self):
		self.mainwindow.mainloop();


if __name__ == '__main__':
	app = MyApp()
	app.run()
```

file: main.ui

```xml
<?xml version='1.0' encoding='utf-8'?>
<interface>
  <object class="tk.Toplevel" id="mainwindow">
    <property name="height">200</property>
    <property name="resizable">both</property>
    <property name="title" translatable="yes">issue174</property>
    <property name="width">200</property>
    <child>
      <object class="ttk.Frame" id="Frame_1">
        <property name="height">200</property>
        <property name="padding">4</property>
        <property name="width">200</property>
        <layout>
          <property name="column">0</property>
          <property name="propagate">True</property>
          <property name="row">0</property>
          <property name="sticky">nsew</property>
          <rows>
            <row id="0">
              <property name="weight">1</property>
            </row>
          </rows>
          <columns>
            <column id="0">
              <property name="weight">1</property>
            </column>
          </columns>
        </layout>
        <child>
          <object class="pygubu.builder.widgets.scrollbarhelper" id="scrollbarhelper_1">
            <property name="scrolltype">both</property>
            <property name="usemousewheel">true</property>
            <layout>
              <property name="column">0</property>
              <property name="propagate">True</property>
              <property name="row">0</property>
              <property name="sticky">nsew</property>
            </layout>
            <child>
              <object class="ttk.Treeview" id="mytree">
                <property name="selectmode">extended</property>
                <property name="show">headings</property>
                <layout>
                  <property name="column">0</property>
                  <property name="propagate">True</property>
                  <property name="row">0</property>
                  <property name="sticky">nsew</property>
                </layout>
                <child>
                  <object class="ttk.Treeview.Column" id="coluser">
                    <property name="column_anchor">w</property>
                    <property name="heading_anchor">w</property>
                    <property name="minwidth">20</property>
                    <property name="stretch">true</property>
                    <property name="text" translatable="yes">Username</property>
                    <property name="tree_column">false</property>
                    <property name="visible">true</property>
                    <property name="width">200</property>
                  </object>
                </child>
                <child>
                  <object class="ttk.Treeview.Column" id="colscore">
                    <property name="column_anchor">w</property>
                    <property name="heading_anchor">w</property>
                    <property name="minwidth">20</property>
                    <property name="stretch">true</property>
                    <property name="text" translatable="yes">Score</property>
                    <property name="tree_column">false</property>
                    <property name="visible">true</property>
                    <property name="width">100</property>
                  </object>
                </child>
              </object>
            </child>
          </object>
        </child>
        <child>
          <object class="ttk.Frame" id="Frame_2">
            <property name="height">200</property>
            <property name="padding">5</property>
            <property name="width">200</property>
            <layout>
              <property name="column">1</property>
              <property name="propagate">True</property>
              <property name="row">0</property>
              <property name="sticky">n</property>
              <rows>
                <row id="0">
                  <property name="pad">5</property>
                </row>
                <row id="1">
                  <property name="pad">5</property>
                </row>
              </rows>
            </layout>
            <child>
              <object class="ttk.Button" id="Button_1">
                <property name="command">on_populate_action</property>
                <property name="text" translatable="yes">Populate</property>
                <layout>
                  <property name="column">0</property>
                  <property name="propagate">True</property>
                  <property name="row">0</property>
                </layout>
              </object>
            </child>
            <child>
              <object class="ttk.Button" id="Button_2">
                <property name="command">on_clear_action</property>
                <property name="text" translatable="yes">Clear</property>
                <layout>
                  <property name="column">0</property>
                  <property name="propagate">True</property>
                  <property name="row">1</property>
                </layout>
              </object>
            </child>
          </object>
        </child>
      </object>
    </child>
  </object>
</interface>
```

**Comment by jpmpdias** [comment]
Hi Alejandro,
Thank you very much for your help.
Problem solved, it turns out it was a problem with my class structure that was feeding the tree, that was not cleaning itself and hence cumulating instances and giving th impression the tree was not erasingThanks for your help,Joao
Joao Dias 

    Le mardi 15 octobre 2019 à 01:37:18 UTC−4, Alejandro Autalán <notifications@github.com> a écrit :  
 
 
Hello Joao, thanks for trying pygubu.
Could you pass an example of reduced code showing the problem? That way I can help you better.
Meanwhile I show you a small example of using treeview and pygubu.

Regards
Alejandro A.

file: main.py
from pathlib import Path
import random
import pygubu

APP_DIR = Path(__file__).resolve().parent

class MyApp:
	def __init__(self):
		self.builder = builder = pygubu.Builder()
		uifile = APP_DIR.joinpath('main.ui')
		builder.add_from_file(uifile)
		self.mainwindow = builder.get_object('mainwindow')
		self.tree = builder.get_object('mytree')
		builder.connect_callbacks(self)
		
	def on_populate_action(self):
		'''Add some items to the treeview.'''
		
		count = random.randint(10, 20)
		for k in range(count):
			num = random.randint(100, 5000)
			username = f'User_{num}'
			score = random.randint(0, 1000)
			self.tree.insert('', 'end', values=(username, score))
		
	def on_clear_action(self):
		'''Remove all items from treeview.'''
		
		children = self.tree.get_children()
		self.tree.delete(*children)
		
	def run(self):
		self.mainwindow.mainloop();


if __name__ == '__main__':
	app = MyApp()
	app.run()
file: main.ui
<?xml version='1.0' encoding='utf-8'?>
<interface>
  <object class="tk.Toplevel" id="mainwindow">
    <property name="height">200</property>
    <property name="resizable">both</property>
    <property name="title" translatable="yes">issue174</property>
    <property name="width">200</property>
    <child>
      <object class="ttk.Frame" id="Frame_1">
        <property name="height">200</property>
        <property name="padding">4</property>
        <property name="width">200</property>
        <layout>
          <property name="column">0</property>
          <property name="propagate">True</property>
          <property name="row">0</property>
          <property name="sticky">nsew</property>
          <rows>
            <row id="0">
              <property name="weight">1</property>
            </row>
          </rows>
          <columns>
            <column id="0">
              <property name="weight">1</property>
            </column>
          </columns>
        </layout>
        <child>
          <object class="pygubu.builder.widgets.scrollbarhelper" id="scrollbarhelper_1">
            <property name="scrolltype">both</property>
            <property name="usemousewheel">true</property>
            <layout>
              <property name="column">0</property>
              <property name="propagate">True</property>
              <property name="row">0</property>
              <property name="sticky">nsew</property>
            </layout>
            <child>
              <object class="ttk.Treeview" id="mytree">
                <property name="selectmode">extended</property>
                <property name="show">headings</property>
                <layout>
                  <property name="column">0</property>
                  <property name="propagate">True</property>
                  <property name="row">0</property>
                  <property name="sticky">nsew</property>
                </layout>
                <child>
                  <object class="ttk.Treeview.Column" id="coluser">
                    <property name="column_anchor">w</property>
                    <property name="heading_anchor">w</property>
                    <property name="minwidth">20</property>
                    <property name="stretch">true</property>
                    <property name="text" translatable="yes">Username</property>
                    <property name="tree_column">false</property>
                    <property name="visible">true</property>
                    <property name="width">200</property>
                  </object>
                </child>
                <child>
                  <object class="ttk.Treeview.Column" id="colscore">
                    <property name="column_anchor">w</property>
                    <property name="heading_anchor">w</property>
                    <property name="minwidth">20</property>
                    <property name="stretch">true</property>
                    <property name="text" translatable="yes">Score</property>
                    <property name="tree_column">false</property>
                    <property name="visible">true</property>
                    <property name="width">100</property>
                  </object>
                </child>
              </object>
            </child>
          </object>
        </child>
        <child>
          <object class="ttk.Frame" id="Frame_2">
            <property name="height">200</property>
            <property name="padding">5</property>
            <property name="width">200</property>
            <layout>
              <property name="column">1</property>
              <property name="propagate">True</property>
              <property name="row">0</property>
              <property name="sticky">n</property>
              <rows>
                <row id="0">
                  <property name="pad">5</property>
                </row>
                <row id="1">
                  <property name="pad">5</property>
                </row>
              </rows>
            </layout>
            <child>
              <object class="ttk.Button" id="Button_1">
                <property name="command">on_populate_action</property>
                <property name="text" translatable="yes">Populate</property>
                <layout>
                  <property name="column">0</property>
                  <property name="propagate">True</property>
                  <property name="row">0</property>
                </layout>
              </object>
            </child>
            <child>
              <object class="ttk.Button" id="Button_2">
                <property name="command">on_clear_action</property>
                <property name="text" translatable="yes">Clear</property>
                <layout>
                  <property name="column">0</property>
                  <property name="propagate">True</property>
                  <property name="row">1</property>
                </layout>
              </object>
            </child>
          </object>
        </child>
      </object>
    </child>
  </object>
</interface>
