### ISSUE TITLE
Dialogs don't show up in Designer

### ISSUE THREAD

**Issue by Cilyan** [alejandroautalan/pygubu#183]
Pygubu Designer works great in most situations, however it doesn't display any included dialogs: Preferences, About, <del>or Quit</del>. When using these menu options, nothing happens, <del>execpt for Quit, where despite the three dots in the menu label, the Designer is closed immediately without warning.</del>

Note: preview does work properly, as well as the "Quit..." question if file was modified.

Environment:
Windows 10
conda 4.8.3
Python 3.8.2
Pygubu 0.9.8.5

Meanwhile: is there a mean to set custom widget into the .ui file directly, as the Preferences window doesn't show up?

**Comment by Cilyan** [comment]
I found a way to get around the custom widget by modifying the config file of Pygubu-designer by hand. That works well. But the preferences window still doesn't show up. Unfortunately, I have no logs showing as to why this happens.

**Comment by alejandroautalan** [comment]
Hi cilyan, thanks for trying pyugubu and for the bug report.
I was able to reproduce the error you mention. It is an error introduced in the latest version.
In the meantime you can use version 0.9.8.4. I will fix it as soon as possible.
