### ISSUE TITLE
Changing a button image

### ISSUE THREAD

**Issue by jimmy2217** [alejandroautalan/pygubu#184]
First of all, I love this app, thank you!
If I created a button with an image. How could I change that image later based on acondition.
Example:
Say I wanted to click a button to connect an Arduino via serial. If initially, when the gui starts, the button has image "False.gif'. When I click it, and the Arduino starts, I want to change the image to "True.gif"
To do this, I need to be able to find the button object in the first place. Which I believe is in:

`self.builder.get_object('button id").config()`

I can import the "True.gif" image like so:

`img = PhotoImage(file = 'Button Pics\\True.gif')`

Then I tried:

`self.builder.get_object('connect_ind').config(image = img)`

This however only seems to change the button to a blank image.

Thank you for the help in advance.

Jamil

**Comment by alejandroautalan** [comment]
Hi Jamil, thanks for trying pygubu.

> Then I tried:
> 
> `self.builder.get_object('connect_ind').config(image = img)`
> 
> This however only seems to change the button to a blank image.
> 
> Thank you for the help in advance.

It seems that the image reference is being lost. Try something like this:

```python
class MyApp:
    
    def __init__(self):
        self.builder = builder = pygubu.Builder()
        builder.add_from_file('myapp.ui')
        self.mainwindow = builder.get_object('mainwindow')
        
        self.button_id = self.builder.get_object('button id")
        # Save a reference of the image here
        self.image_true = PhotoImage(file = 'Button Pics\\True.gif')
        
    def on_activate(self):
        # ... do other stuf
        # change button image
        self.button_id.config(image=self.image_true)
        
    def run(self):
        self.mainwindow.mainloop()

if __name__ == '__main__':
    app = MyApp()
    app.run()
```

Let me know.
Regards.

Alejandro A.

**Comment by jimmy2217** [comment]
Thank you it worked!!
Not sure how the image reference is getting lost, but its curious.
I do however have another question:
Changing a text box test. Every time I try:

`self.builder.get_object('text_box').delete("1", "end")`

It tells me that the index is incorrect. Same with the .insert()

**Comment by jimmy2217** [comment]
Thank you so much. This worked!!!

**Comment by alejandroautalan** [comment]
In the final note of this page is the explanation of the lost reference.
https://effbot.org/tkinterbook/photoimage.htm

Regards
Alejandro A.
