### ISSUE TITLE
The ui2code.py doesn’t seem to work 

### ISSUE THREAD

**Issue by michaelbadcrumble** [alejandroautalan/pygubu#187]
I seem to be having trouble with using the XML to code conversion tool. I feed it the values it’s expecting and nothing comes out.

What should I do?

**Comment by alejandroautalan** [comment]
Hi Michael, thanks for trying pygubu.
You need to pass the ui filename and the widget identifier.

```
usage: ui2code.py [-h] filename [rootwidget]

positional arguments:
  filename    .ui file
  rootwidget  Toplevel widget (default: mainwidow)

optional arguments:
  -h, --help  show this help message and exit
```

Please note that this ui2code app is experimental.
Possibly in a week or two I will release a new version.

Greetings.
Alejandro A.

**Comment by michaelbadcrumble** [comment]
I followed the argument order based on what the tool asked for and got nothing. Is anyone working on the experimental tool?

Follow up question, dose the tool expect the user to run it in root or can I pass the paths to the file and output directory?

Kinda desperate for a converter as the app I’m working on needs to drop its dependency with `PyQt5` as soon as possible.

**Comment by alejandroautalan** [comment]
Fixed. Added new way to generate code.
