### ISSUE TITLE
WARNING:pygubu.builder:Missing callbacks for commands: ['']

### ISSUE THREAD

**Issue by qvdm** [alejandroautalan/pygubu#191]
I get a warning about a missing callback with an empty string as the command, when running my script.  I do not have any empty "command" properties in my UI file.

**Comment by alejandroautalan** [comment]
Hello Quentin, thansk for trying pygubu.

> I get a warning about a missing callback with an empty string as the command, when running my script. I do not have any empty "command" properties in my UI file.

Please, give me more info so I can reproduce the issue.
What operative system are you using?
What method did you use to install pygubu?
Can you provide a minimal example (UI file and code) where this happened?

Regards
Alejandro A.

**Comment by qvdm** [comment]
Hi Alejandro,

As I was trimming my UI and application to minimal size as an example, I managed to isolate the issue to a specific element. It turns out that somehow an empty binding had sneaked into an Entry element:
            <bind add="" handler="" sequence="" />

So, not technically a bug, but it would be nice if the warning could indicate the line # in the UI file where the problem is, since currently it is really hard to isolate the problem area.

**Comment by alejandroautalan** [comment]
Hello Quentin, thanks for the report.
A new version will come out in a few days with new features and this problem solved.

Regards!
Alejandro A.
