### ISSUE TITLE
Notebook.Tabs : changing property on any tab refresh display and get focus on first Tab

### ISSUE THREAD

**Issue by going-striker** [alejandroautalan/pygubu#192]
Hi,

first of all, thanks for the work;
Pygubu is a nice to use and good design way to create usable GUIs using Tkinter

I got a little issue, not that much of a deal, but a little annoying

I have a Frame / TopLevel with a Notebook on it.
I have several Tabs on this Notebook.
And when I'm working on second, or third tab, each time I set a property, it refreshes the view, and focus back on the first Tab
I have to get back again on the Tab I was working on, change a property and redo it all over again

When experimenting my widgets positioning it can be annoying because I change sticky, or size many times

If you don't have time, I'd be happy to do the modification and pull request, if you can advise me a little about what to do and where to do it

Thank you

**Comment by alejandroautalan** [comment]
Hi going-striker, thanks for trying pygubu.

> I got a little issue, not that much of a deal, but a little annoying
> 
> I have a Frame / TopLevel with a Notebook on it.
> I have several Tabs on this Notebook.
> And when I'm working on second, or third tab, each time I set a property, it refreshes the view, and focus back on the first Tab
> I have to get back again on the Tab I was working on, change a property and redo it all over again

Yes, this is an old and annoying bug.
I am working on a new version that will be released in a few days. It will include new features and a fix for this problem.

> If you don't have time, I'd be happy to do the modification and pull request, if you can advise me a little about what to do and where to do it

After the the new version release, I will be grateful if you can test it and report new problems.

Regards!
Alejandro A.

**Comment by going-striker** [comment]
Thanks for your quick answer

OK great, I will wait for your next version then
The issue is not blocking, I can live with it meanwhile

Yeah sure, I'll be glad to make some tests in your new version and report

Let me know as soon as it's ready.

Kind regards.

**Comment by alejandroautalan** [comment]
Fixed.
