### ISSUE TITLE
ttk.ComboBox postcommand attribute only work on dropdown click not on value select

### ISSUE THREAD

**Issue by saorav21994** [alejandroautalan/pygubu#193]
Hello. 
Before we proceed, I want to say that pygubu is an excellent GUI builder for tkinter modules. 
Everything was alright till I got stuck at a particular point and can't make any progress in my project. :(

While using ttk.Combobox, in the postcommand attribute, when i give reference to any function, then that function is not called in realtime. 
Say, I have 3 values in combobox 1, 2, 3, and I need to display the value selected and also change the state attribute of any tk.Entry accordingly.
Now for 1st time if I select any value, then on selecting the value, postcommand is not invoked. When I try to select again from dropdown, then the postcommand will get invoked with the previous selection.

So you can see that there is a lag of 1 click always. What I basically mean  is, **on selecting any value from combobox list postcommand is not executed; rather when you click on combobox again to open the dropdown menu, at that time the postcommand is executed with the previous selected value.**

It will be of immense help if you can look into it as soon as possible, or suggest me some other way to do it, or even ask to me make any changes on the pygubu code.

Thanks in advance.

**Comment by alejandroautalan** [comment]
Hello saorav, thanks for trying pygubu.

> While using ttk.Combobox, in the postcommand attribute, when i give reference to any function, then that function is not called in realtime.

ttk.Combobox postcommand is used to dynamically change the list of options of the combobox. For example when the option list depends on another value.
To listen to the 'select' event, you need to bind a callback to the **\<\<ComboboxSelected\>\>** virtual event (see the Bindings tab for the mycbox combobox in the example).
See the following example. If this is not the case, please provide me a minimal example so I can reproduce your problem.

Regards
Alejandro A.


```python
import os
import random
import pygubu


PROJECT_PATH = os.path.dirname(__file__)
PROJECT_UI = os.path.join(PROJECT_PATH, "issue193.ui")


class Issue193App:
    def __init__(self):
        self.builder = builder = pygubu.Builder()
        builder.add_resource_path(PROJECT_PATH)
        builder.add_from_file(PROJECT_UI)
        self.mainwindow = builder.get_object('mainwindow')
        self.mycbox = builder.get_object('mycbox')
        self.lblview = builder.get_object('lblview')
        
        builder.connect_callbacks(self)
    
    def on_mycbox_selected(self, event=None):
        index = self.mycbox.current()
        val = self.mycbox.get()
        msg = 'You selected option {0} with value {1}'.format(index, val)
        self.lblview.configure(text=msg)
    
    def on_mycbox_postcommand(self, event=None):
        '''Postcommand is used to change options before list display'''
        default = ['A', 'B', 'C', 'D']
        dynamic = random.choice(['F', 'G', 'H'])
        default.append(dynamic)
        self.mycbox.configure(values=default)
    
    def run(self):
        self.mainwindow.mainloop()


if __name__ == '__main__':
    app = Issue193App()
    app.run()
```

file issue193.ui
```xml
<?xml version='1.0' encoding='utf-8'?>
<interface>
  <object id="mainwindow" class="tk.Toplevel">
    <property name="height">200</property>
    <property name="width">200</property>
    <child>
      <object id="mainframe" class="ttk.Frame">
        <property name="height">200</property>
        <property name="width">200</property>
        <layout>
          <property name="column">0</property>
          <property name="propagate">True</property>
          <property name="row">0</property>
        </layout>
        <child>
          <object id="Label_1" class="ttk.Label">
            <property name="text" translatable="yes">Combobox test</property>
            <layout>
              <property name="column">0</property>
              <property name="propagate">True</property>
              <property name="row">0</property>
              <property name="sticky">w</property>
            </layout>
          </object>
        </child>
        <child>
          <object id="mycbox" class="ttk.Combobox">
            <property name="postcommand">on_mycbox_postcommand</property>
            <property name="values">A B C D</property>
            <bind sequence="&lt;&lt;ComboboxSelected&gt;&gt;" handler="on_mycbox_selected" add="" />
            <layout>
              <property name="column">0</property>
              <property name="propagate">True</property>
              <property name="row">1</property>
            </layout>
          </object>
        </child>
        <child>
          <object id="lblview" class="ttk.Label">
            <layout>
              <property name="column">0</property>
              <property name="propagate">True</property>
              <property name="row">2</property>
              <property name="sticky">ew</property>
            </layout>
          </object>
        </child>
      </object>
    </child>
  </object>
</interface>
```

**Comment by saorav21994** [comment]
> ```python
> Issue193App
> ```

I have tried to use <<ComboboxSelected>>  to bind a custom function, but it only works for the first time and not subsequently. I have simplified my code to just fetch and print the current selected value. I am attaching both the ui and py file.

issue193.ui
`
<?xml version='1.0' encoding='utf-8'?>
interface>
  <object class="tk.LabelFrame" id="gmainframe">
    <property name="height">200</property>
    <property name="text" translatable="yes">LabelFrame_1</property>
    <property name="width">200</property>
    <layout>
      <property name="column">0</property>
      <property name="propagate">True</property>
      <property name="row">0</property>
    </layout>
    <child>
      <object class="pygubu.builder.widgets.combobox" id="combobox_4">
        <property name="values">a b c d e f g h i j k l m n o p q r s t u v w x y z a1  ½ ¾ 1¼ 1½  2½</property>
        <layout>
          <property name="column">0</property>
          <property name="propagate">True</property>
          <property name="row">0</property>
          <property name="sticky">nw</property>
        </layout>
      </object>
    </child>
    <child>
      <object class="tk.Button" id="done">
        <property name="command">done</property>
        <property name="text" translatable="yes">Show</property>
        <layout>
          <property name="column">0</property>
          <property name="propagate">True</property>
          <property name="row">1</property>
        </layout>
      </object>
    </child>
    <child>
      <object class="tk.Entry" id="firstEntry">
        <property name="text" translatable="yes">Entry_1</property>
        <property name="textvariable">string:first</property>
        <layout>
          <property name="column">0</property>
          <property name="propagate">True</property>
          <property name="row">2</property>
        </layout>
      </object>
    </child>
    <child>
      <object class="tk.Entry" id="secondEntry">
        <property name="text" translatable="yes">Entry_2</property>
        <property name="textvariable">string:second</property>
        <layout>
          <property name="column">0</property>
          <property name="propagate">True</property>
          <property name="row">3</property>
        </layout>
      </object>
    </child>
  </object>
</interface>
`

Issue193App.py

`import pkg_resources.py2_warn
import pkg_resources
import tkinter as tk
from tkinter import ttk
import ttk
import pygubu
import sys
import os
import math
from pygubu.builder import ttkstdwidgets
from pygubu.builder import tkstdwidgets
from pygubu.builder.widgets import dialog
from pygubu.builder.widgets import editabletreeview
from pygubu.builder.widgets import scrollbarhelper
from pygubu.builder.widgets import scrolledframe
from pygubu.builder.widgets import tkscrollbarhelper
from pygubu.builder.widgets import tkscrolledframe
from pygubu.builder.widgets import pathchooserinput
from pygubu.builder.widgets import combobox



class Application:




    def __init__(self, master):
        self.master = master

        self.builder = builder = pygubu.Builder()

        builder.add_from_file('issue193.ui')
        # builder.add_from_file(os.path.join(
        #     os.environ.get(
        #         "_MEIPASS2",
        #         os.path.abspath(".")
        #     ),
        #     "sample.ui"
        # ))
        self.mainwindow = builder.get_object('gmainframe', master)

        builder.connect_callbacks(self)

        self.combobox = self.builder.get_object('combobox_4')
        self.combobox.bind("<<ComboboxSelected>>", self.comboclick())


    def comboclick(self):
        val = self.builder.get_object('combobox_4')
        print(val.get())

    def done(self):
        val = self.builder.get_object('combobox_4')
        print(val.get())






if __name__ == '__main__':
    root = tk.Tk()
    root.geometry("1366x768")
    app = Application(root)

    root.mainloop()`

**Comment by alejandroautalan** [comment]
hi. quick review from my cell phone.
This line
> self.combobox.bind("<<ComboboxSelected>>", self.comboclick())

Should be:
```
self.combobox.bind("<<ComboboxSelected>>", self.comboclick)
```
And change:
> def comboclick(self):

To
```
def comboclick(self, event):
```
Tryit and let me know.

Regards.
Alejandro A.

**Comment by saorav21994** [comment]
Excellent, it's working.  I needed to add the 'event' parameter. 
Thank you very much. Your reply in such short time is really appreciated.
I am closing this issue.

Here's my email in case you want to contact :: saha.saorav@gmail.com

**Comment by JohnTaylorHK** [comment]
What is the event variable passed callback function? Is it useful?
How can I bind the callbacks in pygubu-designer?

**Comment by alejandroautalan** [comment]
Hello @JohnTaylorHK, thanks for trying pygubu.

> What is the event variable passed callback function? Is it useful? 

The event variable is an object representing the tk event being processed. It has information about the widget, key status, etc. depends on type of event.

See https://tkdocs.com/tutorial/concepts.html#events for more info.

> How can I bind the callbacks in pygubu-designer?

Use the bindings editor. Example:

![Captura desde 2023-11-06 08-59-21](https://github.com/alejandroautalan/pygubu/assets/3482471/d835a21f-70e0-4807-8cce-fa40953c5418)
