### ISSUE TITLE
"Exception: Class "tkcalendar.DateEntry" not mapped" error upon running on IDE

### ISSUE THREAD

**Issue by CarterSnich** [alejandroautalan/pygubu#196]
File "C:\Program Files\Python37\lib\site-packages\pygubu\builder\__init__.py", line 377, in _realize
    raise Exception('Class "{0}" not mapped'.format(cname))
Exception: Class "tkcalendar.DateEntry" not mapped

That's the error I recieved when I tried to run my script on the IDE, but when I was designing the GUI there was seems no problem.
I don't know, maybe I made a mistake following the guide on the wiki on incorporating custom widgets.

The custom widget was the tkcalendar I get from PYPI.

Can you help me fix this please? Thanks.

**Comment by CarterSnich** [comment]
I tried using your custom widget on the wiki, but error still persist.

**Comment by alejandroautalan** [comment]
Hello, CarterSnich thanks for trying pygubu.
I think that you are incorrectly setting the class name of the builder class.

As written on the wiki:

>classname: the unique name of our widget. By convention, we use buildermodule.widgetname to define our widget. This attribute is one that is saved in the .ui file generated. This parameter is very important because pygubu use this to find the module that will be responsible for register the builder class.


For example, I have a project dir like:

```
issue196/
    tkcalendarwidgets.py
    issue196.ui
    testapp.py
```
Where tkcalendarwidgets.py has the definition of the builder classes:

file: tkcalendarwidgets.py
```python
from tkcalendar import Calendar, DateEntry
from pygubu import BuilderObject, register_widget


class DateEntryBuilder(BuilderObject):
    class_ = DateEntry


register_widget('tkcalendarwidgets.dateentry', DateEntryBuilder,
                'DateEntry', ('ttk', 'My Tkcalendar widgets'))
```
Here I register the builder class with: **'tkcalendarwidgets.dateentry** where **tkcalendarwidgets** is the python module name and **dateentry** a unique widget name that I choosed.
(Remember, if you change the classname of the builder, you will need to manually modify the xml ui file or create a new one)

Let me know if this info helps you to solve the issue. Otherwise, give me more information about the errors and your enviroment.

Regards!
Alejandro A.


file: testapp.py
```python
import os
import pygubu


PROJECT_PATH = os.path.dirname(__file__)
PROJECT_UI = os.path.join(PROJECT_PATH, "issue196.ui")


class TestApp:
    def __init__(self):
        self.builder = builder = pygubu.Builder()
        builder.add_resource_path(PROJECT_PATH)
        builder.add_from_file(PROJECT_UI)
        self.mainwindow = builder.get_object('mainwindow')
        builder.connect_callbacks(self)
    

    def run(self):
        self.mainwindow.mainloop()

if __name__ == '__main__':
    app = TestApp()
    app.run()
```

file: issue196.ui
```xml
<?xml version='1.0' encoding='utf-8'?>
<interface>
  <object id="mainwindow" class="tk.Toplevel">
    <property name="height">200</property>
    <property name="width">200</property>
    <child>
      <object id="mainframe" class="ttk.Frame">
        <property name="height">200</property>
        <property name="padding">5</property>
        <property name="width">200</property>
        <layout>
          <property name="column">0</property>
          <property name="propagate">True</property>
          <property name="row">0</property>
        </layout>
        <child>
          <object id="Label_1" class="ttk.Label">
            <property name="padding">0 10</property>
            <property name="text" translatable="yes">A tkcalendar DateEntry Widget:</property>
            <layout>
              <property name="column">0</property>
              <property name="propagate">True</property>
              <property name="row">0</property>
            </layout>
          </object>
        </child>
        <child>
          <object id="dateentry_1" class="tkcalendarwidgets.dateentry">
            <layout>
              <property name="column">0</property>
              <property name="propagate">True</property>
              <property name="row">1</property>
            </layout>
          </object>
        </child>
      </object>
    </child>
  </object>
</interface>
```

**Comment by CarterSnich** [comment]
Oh, man. Gee. Thanks! I just didn't understand the guide on the wiki pretty well.

**Comment by CarterSnich** [comment]
Last problem XD:
I created a Dialog widget, but the buttons are not working. I have already set the callbacks, just like how I did on the main window buttons. Is connecting callbacks from a Dialog widget differs from connecting callbacks from the main window?

**Comment by CarterSnich** [comment]
Okay. I figure it out.
code:
def add_student(self):
        callbacks = {
                'ssssssssssss' : self.ssssssssssss
            }
        self.builder.connect_callbacks(callbacks)
        self.add_student_window.run()

I just re connect the callbacks. Is this the proper way?

**Comment by alejandroautalan** [comment]
Hello. Yes, that is one way to use callbacks.
For more info see this page https://github.com/alejandroautalan/pygubu/wiki/CommandProperties

Regards
Alejandro A.
