### ISSUE TITLE
Code script generation for changing "minsize" of Toplevel is missing a period

### ISSUE THREAD

**Issue by nalabrie** [alejandroautalan/pygubu#197]
Creating a `tk.Toplevel` (I named it "top") and changing the `minsize` to something (I used 640x480) will result in the Python code generator to generate the command `topminsize(640, 480)` rather than `top.minsize(640, 480)`.

**Comment by alejandroautalan** [comment]
Hello Nicky, thanks for trying pygubu and for the bug report.
I will fix it ASAP

Regards!
Alejandro a.
