### ISSUE TITLE
Change frame class from gui

### ISSUE THREAD

**Issue by bojomojo** [alejandroautalan/pygubu#199]
Can we have the possibility to override the frame class?
I want to have a child class from the frame class that could go through  all children and disable them when needed. 
And I want to be able to use this class from the designer. 
However the designer doesn't allow To change the class field.

**Comment by alejandroautalan** [comment]
Hi bojomojo.
You can add your custom widgets to the designer. Unfortunately the documentation is not yet complete.
Try to follow this guide (https://github.com/alejandroautalan/pygubu/wiki/IncorporateCustomWidget) and if you have any questions don't hesitate to contact me.

Regards
Alejandro A

**Comment by bojomojo** [comment]
I did try to add the scrolledText widget the same way. But could not find it in the list of widgets to use.
This “custom” option was not there.
(Using it on mac)

Sent from my iPhone

On 12. Jun 2020, at 00:46, Alejandro Autalán <notifications@github.com> wrote:

﻿

Hi bojomojo.
You can add your custom widgets to the designer. Unfortunately the documentation is not yet complete.
Try to follow this guide (https://github.com/alejandroautalan/pygubu/wiki/IncorporateCustomWidget) and if you have any questions don't hesitate to contact me.

Regards
Alejandro A

**Comment by alejandroautalan** [comment]
Hi, maybe you were wrong in the parameter setting?
Did you added the module in the pygubu-designer preferences?
Check out this similar issue https://github.com/alejandroautalan/pygubu/issues/196

Regards
Alejandro A.

**Comment by bojomojo** [comment]
I am trying to use the officially released scrolledtext.py widget.. would this not work out of the box

[cid:b2fe6594-d2f8-477c-a313-2e062e64107a]

Best Regards,
Shadi


________________________________

**Comment by alejandroautalan** [comment]
I'm closing this issue. Changing the class field from designer is not allowed.
