### ISSUE TITLE
Couldn't find pygubu-designer.exe 

### ISSUE THREAD

**Issue by Vikash15081999** [alejandroautalan/pygubu#200]
Hi,

I am window 7 user, I have installed pygubu using command in command prompt "pip install pygubu".

Python version: 3.6.5

But I couldn't find the designer.exe file in python script folder or in user python script folder.

I can even import pygubu in IDLE. can you please send me the that designer.exe file alone to my mail.

Can you kindly help me Please

Thanks in advance.

Vikash

**Comment by alejandroautalan** [comment]
Hi Vikash, thanks for trying pygubu, and sorry for the late response.
Since version 0.10 the project was splitted in two main modules, to install the designer type the following in a windows console command:

    pip install pygubu-designer

Regards.
Alejandro A

**Comment by Vikash15081999** [comment]
Thank you so much I got it.

Vikash
