### ISSUE TITLE
Scrolled frame can not resize in latest version of pygubu-designer

### ISSUE THREAD

**Issue by OliverXie05** [alejandroautalan/pygubu#204]
Hello!

I was using pygubu-designer on my laptop in a version probably released one year ago to build a scrolled frame, I followed the instruction from issue #50 and used the framesizer method. It worked perfectly. However, when I transferred my code to my desktop which has the latest version of pygubu-designer, the scrolled frame becomes fixed size again even if the sticky is nsew and weights for row and column 0 are 1. Is it the new version causing the issue or something else?
The top one is from the new version designer and the other is the old one. I just copied the code from issue #50 for both.
![issue1](https://user-images.githubusercontent.com/49598363/89743234-c97aa980-da66-11ea-9762-2327a9e9180d.png)
![image](https://user-images.githubusercontent.com/49598363/89743242-dac3b600-da66-11ea-8a01-c17c03eee7c6.png)

**Comment by alejandroautalan** [comment]
Hello Oliver, thanks for trying pygubu and your report.
I think that it is a bug introduced when I added support for multiple layout manager methods.
I will try to fix it ASAP.

Regards
Alejandro A.

**Comment by OliverXie05** [comment]
Is the bug fixed?

**Comment by alejandroautalan** [comment]
Hi. It's fixed in the master branch. There is no pypi release yet.
For older files maybe you need to open them and adjust some grid options.
For the issue #50 UI example, it's working.
If You can, test it using the Master branch.
Next version will be available soon.

Regards,
Alejandro A.

**Comment by OliverXie05** [comment]
Thank you so much!
