### ISSUE TITLE
File "pygubu-designer.exe" doesn't exist.

### ISSUE THREAD

**Issue by mikecodre** [alejandroautalan/pygubu#205]
I did: 
-python setup.py install
-pip install pygubu
-import pygubu
All successfully completed. 
What do I do next? I can't find the pygubu-designer.exe file anywhere. I searched in the pycharm and the python folders.
Python version: 3.8.5
Windows version: Windows 10 2004
IDLE: Pycharm

**Comment by alejandroautalan** [comment]
Hi mikecodre, thanks for trying pygubu.
You need to install the designer:

    pip install pygubu-designer

Since version 0.10 the project was splitted in two modules.

Regards
Alejandro A.

**Comment by mikecodre** [comment]
Thanks. Problem solved! I'm closing this issue.
