### ISSUE TITLE
How do I change the Rows and Columns of a widget?

### ISSUE THREAD

**Issue by 2briancox** [alejandroautalan/pygubu#206]
In a previous version of Pygubu-designer I was able to change the Rows and Columns of a Widget under "Layout".  But no more with the newest version; 0.10.2.

Everything comes in as Row 0, Column 0 and I cannot figure out how to change it.

**Comment by 2briancox** [comment]
Ok, I don't know what was happening, but earlier under "Manager" within "Layout" I only saw...

pack
place

But not suddenly I also have the option of "grid".  So it is working now.

**Comment by shenlebantongying** [comment]
For future reference:

You need 3 or more widgets to enable the "grid" in the manager.

If you only have 1 or 2 widigts, the pygubu will only let you use "pack" and "place".

**Comment by alejandroautalan** [comment]
Hi shenlebantongying, thanks for trying pygubu.

> I know someone would search to here, for future reference:
> 
> You need 3 or more widgets to enable the "grid" in the manager.
> 
> If you only have 1 or 2 widigts, the pygubu will only let you use "pack" and "place".

That is not correct. Inside a container widget, the manager types available for select will depend on the manager type choosed for the first child widget.
See this example https://github.com/alejandroautalan/pygubu-designer/issues/4#issuecomment-719982525

Regards.
Alejandro A.
