### ISSUE TITLE
Can not run pygubu-designer ver 0.10.2

### ISSUE THREAD

**Issue by santi2fx** [alejandroautalan/pygubu#207]
I try run pygubu-designer.exe 
![1600793386712](https://user-images.githubusercontent.com/36126692/93912744-584d3800-fd2e-11ea-8135-9cd154d28c5b.jpg)

Please Please ....Help me too.

**Comment by alejandroautalan** [comment]
Hello santi2fx, thanks for trying pygubu.

Please provide more info so I can help you.
- Can you see an error message?
- How did you install pygubu-designer?
- Did you have a previous version installed?
- Open a console terminal. What is the output of the following command?

        python -m pygubudesigner

Try to uninstall pygubu and pygubu-designer:

    pip uninstall pygubu
    pip uninstall pygubu-designer

Go to the python install path and remove all remaining files (if any remains) related to pygubu. Then install again.

    pip install pygubu-designer

Let me know if this helps.

Regards
Alejandro A.

**Comment by santi2fx** [comment]
**Can you see an error message?**
   I do not see the error.

**How did you install pygubu-designer?**
Try 1 ==>python setup.py install
Try 2 ==> pip install pygubu and pip install pygubu-designer

**Did you have a previous version installed?**
   Yes, I don't remember version, but I used April 2020.

 Open a console terminal. What is the output of the following command?
   See attached pig.
![pip install pygubu-designer](https://user-images.githubusercontent.com/36126692/93977862-56728b80-fda5-11ea-98ff-9b2a13d14499.jpg)
![pip uninstall pygubu](https://user-images.githubusercontent.com/36126692/93977868-596d7c00-fda5-11ea-8b11-68893de3a81c.jpg)
![pip uninstall pygubu-designer](https://user-images.githubusercontent.com/36126692/93977878-5b373f80-fda5-11ea-86fe-eda28de50174.jpg)
![python -m pygubudesigner](https://user-images.githubusercontent.com/36126692/93977887-5ecac680-fda5-11ea-96ea-59d454b61235.jpg)

**Comment by alejandroautalan** [comment]
Hello, sorry for the late response.
Delete the old configuration file shown in the last image:

    c:\Users\santi\AppData\Local\pygubu-designer\pygubu-designer\config

Or remove the entire directory (c:\Users\santi\AppData\Local\pygubu-designer)
After that, pygubu-designer should start normally.
I will add some verification to inform future users and avoid this problem.

Let me know if this works.

Regards
Alejandro A.

**Comment by santi2fx** [comment]
Very excellent,

![pygubu-designer](https://user-images.githubusercontent.com/36126692/94040373-0f12ec00-fdf3-11ea-8bb7-509f101facdf.jpg)
