### ISSUE TITLE
PYGUBU designer not working

### ISSUE THREAD

**Issue by p20180014** [alejandroautalan/pygubu#210]
https://github.com/alejandroautalan/pygubu/issues/45#issue-61732839

Same Issue as in the previous one but for Ubuntu 20.04 and pythn 3.7.4

**Comment by alejandroautalan** [comment]
Hello p20180014 thanks for trying pygubu.
Please describe the steps you performed on your computer.
Remember that, as indicated in the README, the designer was moved to a separate repository. You have to install it with:

    pip install pygubu-designer

Regards
Alejandro A.
