### ISSUE TITLE
Insert text to Scrolledtext

### ISSUE THREAD

**Issue by santi2fx** [alejandroautalan/pygubu#214]
Please help me.

I try insert text to ScrolledText.

tkinterscrolledtext_1 = self.builder.get_object('tkinterscrolledtext_1')
tkinterscrolledtext_1.insert(0, 'Hello My App')

**Comment by alejandroautalan** [comment]
Hi santi2fx, thanks for trying pygubu.

> I try insert text to ScrolledText.
> 
> tkinterscrolledtext_1 = self.builder.get_object('tkinterscrolledtext_1')
> tkinterscrolledtext_1.insert(0, 'Hello My App')

You specified an incorrect index. It should be:

    tkinterscrolledtext_1.insert('0.0', 'Hello My App')

![Captura de pantalla_2020-10-25_21-56-18](https://user-images.githubusercontent.com/3482471/97124088-85b24a80-170d-11eb-875c-50c55f0eb615.png)


See [this](https://tkdocs.com/shipman/text-index.html) for more info.

Regards
Alejandro A.

**Comment by santi2fx** [comment]
Thank you very much

ในวันที่ จ. 26 ต.ค. 2020 เวลา 08:03 Alejandro Autalán <
notifications@github.com> เขียนว่า:
