### ISSUE TITLE
How take values from .ui file (entry or spinbox) to matplotlib?

### ISSUE THREAD

**Issue by Doid-Reyewliz** [alejandroautalan/pygubu#221]

**Comment by alejandroautalan** [comment]
Hi Doid, sorry for the late response.
I made an example for you on how to handle user input with basic widgets.  [here](https://github.com/alejandroautalan/pygubu-designer/tree/master/examples/user_input)
Don't forget to review the [wiki](https://github.com/alejandroautalan/pygubu/wiki) for a pygubu overview and common usage tips.

Regards
Alejandro A.
