### ISSUE TITLE
Can not open pygubu-designer

### ISSUE THREAD

**Issue by George31415926** [alejandroautalan/pygubu#222]
C:\Users\"my user"\PycharmProjects\Simple_GUI>pygubu-designer
'pygubu-designer' is not recognized as an internal or external command,
operable program or batch file.

I have pip installed the pygubu-designer to the same directory.

Please help?

**Comment by alejandroautalan** [comment]
Hi George, thanks for trying pygubu. Sorry for the late response.

- What python version are you using?
- Do you have Python in the Windows Path?
- After "pip install pygubu-designer" the executable is installed in the "script" folder of your python installation. For exampe, if you have python installed in C:\Python38, pygubu-designer is installed in C:\Python34\Scripts\pygubu-designer.exe
- Alternatively you can run the following command:

        python -m pygubudesigner

Let me know if this help.
Regards.
Alejandro A.

**Comment by George31415926** [comment]
Hi, thanks for getting back to me.

.Python 3.9
.When I installed it via cmd I first changed the directory to my scripts
folder in my PyCharm, this is something I had to do with my other modules
to get them to work... I am rather new to all this so this could well be an
error on my part.

Kind Regards,
George
