### ISSUE TITLE
what's the different between pygubu and pygubu-designer？

### ISSUE THREAD

**Issue by 0400H** [alejandroautalan/pygubu#223]
Reference:
https://github.com/alejandroautalan/pygubu
https://github.com/alejandroautalan/pygubu-designer

As shown above, I am confused about this.

**Comment by alejandroautalan** [comment]
Hello 0400H, thanks for trying pygubu.

- **pygubu** is the core library that creates tkinter interfaces from its definition in xml.
- **pygubu-designer** is the program that allows you to design interfaces in a graphic way and save them in xml format, to be used with pygubu.

Regards
Alejandro A.
