### ISSUE TITLE
pyinstaller generated exe fails with error: ModuleNotFoundError: No module named 'pygubu.builder.tkstdwidgets

### ISSUE THREAD

**Issue by djscottyp** [alejandroautalan/pygubu#226]
I've tried adding the following lines to my code per the closed issue:
`from pygubu.builder import ttkstdwidgets`

I've tried adding the pygubu.builder.ttkstdwidgets by adding it to the command line as suggested elsewhere:
`pyinstaller go.py --onefile --hidden-import "pygubu.builder.ttkstdwidgets" --version-file file_version_info-temp.txt --add-data "goiniEditor.ui;."`

When my code gets to calling the GUI, it fails with the moduleNotFoundError in the subject.

**Comment by alejandroautalan** [comment]
Hello djscottyp, thanks for trying pygubu.

You need to create a Spec file for your app.  There is an example here [Pygubu Pyinstaller example](https://github.com/alejandroautalan/pygubu-designer/tree/master/examples/pyinstaller)

If you have more errors, show me the full error message.
Let me know.

Regards
Alejandro A.

**Comment by djscottyp** [comment]
I really don’t understand why using the spec file works over using the commandline but, it got me there.  Thank you for the excellent work on the GUI designer… I must have spent 20+ hours working on how to create a gui with tkinter before I found your designer.  I spent 4 hours creating and updating the GUI and most of that was spent watching your YouTube video and walking through it myself.  Your RAD is rad!! Sent from Mail for Windows 10 From: Alejandro AutalánSent: Wednesday, January 20, 2021 11:58 AMTo: alejandroautalan/pygubuCc: djscottyp; AuthorSubject: Re: [alejandroautalan/pygubu] pyinstaller generated exe fails with error: ModuleNotFoundError: No module named 'pygubu.builder.tkstdwidgets (#226) Hello djscottyp, thanks for trying pygubu.You need to create a Spec file for your app. There is an example here Pygubu Pyinstaller exampleIf you have more errors, show me the full error message.Let me know.RegardsAlejandro A.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by alejandroautalan** [comment]
Glad it worked.
Thanks for your words! They push me to keep improving pygubu.

Regards!
Alejandro A.
