### ISSUE TITLE
Supporting Version of pygubu

### ISSUE THREAD

**Issue by sw08** [alejandroautalan/pygubu#228]
Hello.
I saw "Python >= 2.7" at readme.md
Then I can't use pygubu at python 3?

**Comment by alejandroautalan** [comment]
Hello sw08, thanks for trying pygubu.

Pygubu should work in all python versions starting from  2.7 and above.
You can use pygubu with python 3.

Regards.
Alejandro A.

**Comment by sw08** [comment]
ok
Thanks
