### ISSUE TITLE
NameError: name 'true' is not defined

### ISSUE THREAD

**Issue by leoheck** [alejandroautalan/pygubu#233]
Using pygubu v0.10.5

This is autogenerated with CustomWidget
```
self.tkscrollbarhelper2_2.configure(borderwidth='2', usemousewheel=true)
NameError: name 'true' is not defined
```

**Comment by alejandroautalan** [comment]
Hi Leonardo, thanks for trying pygubu and for the bug report.
I will fix it ASAP.

Regards
Alejandro A.

**Comment by leoheck** [comment]
Wow, pretty fast.
