### ISSUE TITLE
How to use container option in Code generated ?

### ISSUE THREAD

**Issue by MHarlock** [alejandroautalan/pygubu#239]
Hi,
I can't understand how use generated code script in pygubu-builder, expecially this line

self.dupe_top_win = tk.Tk(, container='false') if master is None else tk.Toplevel(master, container='false')

What's first parameters ? 
Moreover Pytohn3 don't accept container='false' parameter 

  File "/Users/user/Dev/Dupe/tk/dupe_top_win_code_script.py", line 8, in __init__
    self.dupe_top_win = tk.Tk(master, container='false') if master is None else tk.Toplevel(master, container='false')
TypeError: __init__() got an unexpected keyword argument 'container'

My system is a macOs 10.15, Python 3.9 and I use Pycharm.
Any hints ?
Thanks

**Comment by rdbende** [comment]
You got this error message because `tk.Tk` instance really doesn't have the argument `container`.

If we look at the source code for `__init__` for `tk.Tk()` it looks like this:

```python
def __init__(self, screenName=None, baseName=None, className='Tk', useTk=1, sync=0, use=None):
```
so it doesn't accept the container argument.

But tk.Toplevel have container argument (and some useful other, I don't know, why `tk.Tk` isn't consistent with `tk.Toplevel`):

```
background, bd, bg, borderwidth, class, colormap, container,
cursor, height, highlightbackground, highlightcolor,
highlightthickness, menu, relief, screen, takefocus,
use, visual, width
```

This argument is False by default, so I don't know, why Pygubu uses it.
If you want to know what the container argument actually is: https://www.tcl.tk/man/tcl8.4/TkCmd/toplevel.htm#M9

**Comment by alejandroautalan** [comment]
Hello MHarlock, thanks for trying pygubu.

> Hi,
> I can't understand how use generated code script in pygubu-builder, expecially this line
> 
> self.dupe_top_win = tk.Tk(, container='false') if master is None else tk.Toplevel(master, container='false')

This is a code generation error in the designer.  I will fix it ASAP. If container property is set it should generate:

    self.dupe_top_win = tk.Toplevel(master, container='false')

> What's first parameters ?
> Moreover Pytohn3 don't accept container='false' parameter
> 
> File "/Users/user/Dev/Dupe/tk/dupe_top_win_code_script.py", line 8, in **init**
> self.dupe_top_win = tk.Tk(master, container='false') if master is None else tk.Toplevel(master, container='false')
> TypeError: **init**() got an unexpected keyword argument 'container'
> 
> My system is a macOs 10.15, Python 3.9 and I use Pycharm.
> Any hints ?
> Thanks

As rbende said in https://github.com/alejandroautalan/pygubu/issues/239#issuecomment-807486126, **container**  is a special property of Toplevel.

**Comment by MHarlock** [comment]
Hi Alejandro,
Yes I know that container is a Toplevel tcl-tk but I think that is not implemented in python tkinter as say rdbende

> But tk.Toplevel have container argument (and some useful other, I don't know, why `tk.Tk` isn't consistent with `tk.Toplevel`):
> 
> ```
> background, bd, bg, borderwidth, class, colormap, container,
> cursor, height, highlightbackground, highlightcolor,
> highlightthickness, menu, relief, screen, takefocus,
> use, visual, width
> ```
> 
> This argument is False by default, so I don't know, why Pygubu or you need to specify it.
> If you want to know what the container argument actually is: https://www.tcl.tk/man/tcl8.4/TkCmd/toplevel.htm#M9

**Comment by rdbende** [comment]
No, it's implemented in tkinter as well, try this:

```python
top1 = tk.Toplevel(container=True)
top1.title('Top1')

top2 = tk.Toplevel(use=top1.winfo_id())
top2.title('Top2')

button = ttk.Button(top2, text='Button')
button.pack()
```

**Comment by MHarlock** [comment]
Right,
now start to understand
Thanks
