### ISSUE TITLE
Fixed. Added new way to generate code. - not reference in documentation  

### ISSUE THREAD

**Issue by Zzetetic** [alejandroautalan/pygubu#242]
Fixed. Added new way to generate code.

_Originally posted by @alejandroautalan in https://github.com/alejandroautalan/pygubu/issues/187#issuecomment-633800227_
and here
https://github.com/alejandroautalan/pygubu/issues/130#issuecomment-633799766

There is no mention of the new functionality in the documentation and therefore it is not clear how to do what was previously done using ui2code.py. 

ui2code.py has been removed from the code.

**Comment by themegabyte** [comment]
@alejandroautalan Can you please elaborate what is the new way of code generation that is not documented?

Many thanks.

**Comment by alejandroautalan** [comment]
Hello themegabyte, thanks for trying pygubu.

For code generation you need to install the latest version of [pygubu-designer](https://github.com/alejandroautalan/pygubu-designer).
Once you have finished the design of your app, you can generate code based on three templates:

**Application**: generates the "main" python program for load the GUI, the code uses the XML definition of the GUI.

**Code Script**: generates the main python program but with a "coded" version of the XML GUI definition.

**Custom Widget**: creates a base class for a custom widget.

This are options that still are in development (that is why are not announced or documented), but can be used with caution.

![Captura de pantalla_2021-08-15_21-37-56](https://user-images.githubusercontent.com/3482471/129498103-16629f73-9917-40b4-a442-ec4e7bc8d587.png)


Let me know if you have more questions.

Regards
Alejandro A.
