### ISSUE TITLE
Use of old string formatting

### ISSUE THREAD

**Issue by MoeinMavini** [alejandroautalan/pygubu#243]
I am using python 3.7.8 and all strings with %s in them just shows %s in output, it works fine if i replace %s with {}.
I don't know what is the solution that works in all python versions, if pygubu reaches a conclusion i am willing to apply it.

I searched some and it seems `from string import Template` and string concatenation are two methods that can't fail.

**Comment by MoeinMavini** [comment]
The easier way is using `'%s %s' % ('one', 'two')`. this works from 2.7 to 3.8

**Comment by alejandroautalan** [comment]
Hello Moein, thanks for trying pygubu and sorry for the late response.

- What OS are you using?
- Can you post an example (or screenshot) of the text that shows "%s" ?

> The easier way is using `'%s %s' % ('one', 'two')`. this works from 2.7 to 3.8

I think that the best will be using the style:

    "This is line {0}".format(line)"

But I need to know which strings have this problems. Let me know.

Regards
Alejandro A.

**Comment by MoeinMavini** [comment]
Hi, i am using a fork: pygubu 0.11, designer 0.10, on Windows.
I modified pygubu-designer\examples\button_cb.py to make image:

![bandicam 2021-06-29 06-51-10-140](https://user-images.githubusercontent.com/30869730/123727502-fd410680-d8a6-11eb-9902-b1a4279d7dab.jpg)

All strings with %s in them have the problem since modulo style is not supported in 3.6 forwards.

**Comment by alejandroautalan** [comment]
Oh you mean the code in the examples. I don't have tests for them so they got outdated.
Yes, If you want to update please use the style:  "This is line {0}".format(line)

Let me know.
Regards.
Alejandro A.

**Comment by MoeinMavini** [comment]
Ok there was only 2 old style formattings in main that i am gonna create a pull request for that but while i was cheking i found that In pygubudesigner\Previewer.py line 97 and 98 there is this:
`xpath = ".//object[@class='ttk.Notebook.Tab']"
xpath = xpath.format(select_id)`
{0} is missing.

**Comment by MoeinMavini** [comment]
There was no problem in pygubu, i saw those 2 in designer main and i though there should be more but there wasn't.
Sorry over estimated.
