### ISSUE TITLE
Possible bug with script generator

### ISSUE THREAD

**Issue by javageek68** [alejandroautalan/pygubu#251]
I created a resizable dialogue box in the designer.  Resizing worked correctly in the preview within PyGubu.  The child frame and the textbox resized when the user resized the parent frame.  

Then I used the Code Script tab to generate code.  When I ran the script from Python, it did not resize correctly.  When the user resized the parent frame the child frame and the textbox did not resize.  

I attached a zip file with the original ui file and the Python script it generated.

[PyGuBu.zip](https://github.com/alejandroautalan/pygubu/files/7741363/PyGuBu.zip)
.

**Comment by alejandroautalan** [comment]
Hello javageek68, thanks for trying pygubu.

Some notes about the test_app.ui file:

* You need to make the 'frame_parent' resizable setting weight=1 to the row 0 and column 0 of the grid manager.

Yes, It seems that there is a bug when showing the preview with the F5 key. But if you try to resize the window using the design view, it shows that the frame is not resizable.

The code generation seems to be working ok.

I made a video showing how to fix the layout.

https://user-images.githubusercontent.com/3482471/146771968-38b8f5a6-3486-4fa6-b950-3dc6390b59b5.mp4

Let me know.

Regards
Alejandro A.

**Comment by javageek68** [comment]
Thanks for your help!  

BTW, this app is a life saver!
