### ISSUE TITLE
delete this wiki page?

### ISSUE THREAD

**Issue by matecsaj** [alejandroautalan/pygubu#255]
American English chose to be the language used for documenting pygubu. The English version of this information has already moved here https://github.com/alejandroautalan/pygubu-designer/wiki/Design-Reuse.  

Should this wiki page be deleted, and if so, please do so?
https://github.com/alejandroautalan/pygubu/wiki/IncorporateCustomWidget.es

**Comment by alejandroautalan** [comment]
Page removed.
