### ISSUE TITLE
pygubu on conda-forge

### ISSUE THREAD

**Issue by dact221** [alejandroautalan/pygubu#256]
Dear developers,

Could you please publish pygubu on conda-forge?

Many people use conda for package installation/management. Providing pygubu only through pypi currently makes it impossible to implement it as a dependency on conda packages (see [conda-build issue #548](https://github.com/conda/conda-build/issues/548)).

Creating a conda-forge recipe for a PyPI package like pygubu seems easy (see [conda-forge site](https://conda-forge.org/#add_recipe)). There is [Grayskull](https://github.com/conda-incubator/grayskull), a conda recipe generator (also available [online](https://www.marcelotrevisani.com/grayskull)).

**Comment by alejandroautalan** [comment]
Hello @dact221, thanks for trying pygubu.
I started to read the documentation to submit a recipe for pygubu.
I need to make some modifications to the pygubu source to complete the build process of conda and then submit the recipe.

Regards
Alejandro A.

**Comment by najacobs** [comment]
Hi, 
Are you still planning to do this? Would really prefer to use conda install for all packages and I need pygubu for the software I am running.

**Comment by alejandroautalan** [comment]
Hello @najacobs, thanks for trying pygubu.
I'm new with conda and the CI packaging process. I managed to add a [PR](https://github.com/conda-forge/staged-recipes/pull/27245) but I will need some help to make this work.

Regards
Alejandro A.

**Comment by alejandroautalan** [comment]
Added pygubu package on [conda-forge](https://github.com/conda-forge/pygubu-feedstock)
