### ISSUE TITLE
Trying to create executable: Old links to example files gets 404 error

### ISSUE THREAD

**Issue by LalFX** [alejandroautalan/pygubu#258]
I am trying to create an executable and was doing some research on the "issues" pages when I ran into a problem. All the old links to the example code seems to have changed and I get a 404 error. Could you share the new links?

For reference, one of the links is: https://github.com/alejandroautalan/pygubu-designer/tree/master/examples/pyinstaller

Most of the links provided for further information do not seem to work now.

**Comment by rdbende** [comment]
> For reference, one of the links is: https://github.com/alejandroautalan/pygubu-designer/tree/master/examples/pyinstaller

Here are the executable creation examples: 
- [pyinstaller](https://github.com/alejandroautalan/pygubu-designer/tree/master/examples/integration_with_pyinstaller)
- [cxFreeze](https://github.com/alejandroautalan/pygubu-designer/tree/master/examples/integration_with_cxFreeze)
- [nuitka](https://github.com/alejandroautalan/pygubu-designer/tree/master/examples/integration_with_nuitka)
- [py2exe](https://github.com/alejandroautalan/pygubu-designer/tree/master/examples/integration_with_py2exe)

**Comment by LalFX** [comment]
Thanks so much. Was this listed somewhere that I missed?
