### ISSUE TITLE
pygubu example with frame and menu ?

### ISSUE THREAD

**Issue by hemmerling** [alejandroautalan/pygubu#26]
Hello,
I checked the examples,
BUT I failed to generate the well known standard GUI application on any platform which usually combine:
- Frame ( "commands.ui" )
- Menus at the  top of the Frame ( "menuexample.ui" )

and I did not find any example in the examples folder.

Indeed pygubu offers with "commands.ui" an example how to put menus at any place on the screen, but I don´t see that I can generate the same effect as done do with your "menuexample.ui" and as I know from the SpecTcl Designer
http://www.sourceforge.net/projects/spectcl

I already tested to move around some of the XML code, but without positive effect.

May you, the developer or the users, help me :-)?! With a working project example?
Or are there techncial Python Tkinter constrains which prevent that ?! As I said, SpecTCL designer generates code which does it, so it must be possible but who know if in the Tkinter mode used here...

Sincerely
Rolf

**Comment by odds-get-evened** [comment]
is the same applicable to ttk.Menubutton? for some reason I cannot figure out how to get a menu into it.
