### ISSUE TITLE
cannot add frames to notebook widget

### ISSUE THREAD

**Issue by mintaka5** [alejandroautalan/pygubu#261]
as the topic suggests. in code you can assign widgets to the notebook instance, but how do you accomplish this in Pygubu? seems the additional frames get placed outside of the notebook, and expecting them to be children of the notebook instance.
![image](https://user-images.githubusercontent.com/87902810/170087823-39f2131f-a68b-4042-84c2-852c284278f7.png)

**Comment by alejandroautalan** [comment]
Hello @mintaka5, thanks for trying pygubu.
You need to use the Notebook.Tab helper. Located in Pygubu Helpers.

![Captura de pantalla_2022-05-24_13-44-46](https://user-images.githubusercontent.com/3482471/170089236-bc0b02c1-a9e0-4de5-b0e8-a4ca6f92f8a2.png)

Regards
Alejandro A.
