### ISSUE TITLE
i want to change text color with a funtion but it doesn't work

### ISSUE THREAD

**Issue by Fefedu973** [alejandroautalan/pygubu#272]
i want to change text color with a funtion but it doesn't work
![image](https://user-images.githubusercontent.com/80718477/190901914-dd1fa092-acd1-4506-b586-03418aabcfca.png)

**Comment by alejandroautalan** [comment]
Hello @Fefedu973.  Sorry, I can't see all context here.  Please paste more code or a link to your repository.

Regards

**Comment by Fefedu973** [comment]
Hi my issue is fixed
