### ISSUE TITLE
Can I move all widgets assigned to a row down one row?

### ISSUE THREAD

**Issue by AJ6CU** [alejandroautalan/pygubu#276]
Hi,

Have a bunch of widgets laid out in a grid. And of course, I remember that I forgot one and need to add a new one in first row. I know I can individually select each widget and move them down in their layout tab. But is there a way to select a bunch of widgets and move them all down at once?

thanks!

Mark

**Comment by alejandroautalan** [comment]
Hello @AJ6CU, thanks for trying pygubu.

>  But is there a way to select a bunch of widgets and move them all down at once?

I realized that you can do that, just select the widgets and use the keyboard shortcuts Alt+[I, K, J, L]. But, you can change the position in the grid not the position in the tree (only individually, maybe I will add a fix for this).
Example:

https://user-images.githubusercontent.com/3482471/201814262-9291f85d-47c6-4f4b-98aa-1141491db8bf.mp4

Regards!
Alejandro A.

**Comment by AJ6CU** [comment]
Thanks! That works!  Although no big thing, being able to re-arrange the position in the tree would be nice if that was reflected in the generated code.  Then I could group things together and find them more quickly. But not real important. Before I am done, the generated code is going to have to be a black box as it will be too complex anyway.

**Comment by alejandroautalan** [comment]
> Thanks! That works!

Great!

Regards!
