### ISSUE TITLE
 Tag Issue when packaging

### ISSUE THREAD

**Issue by yuzibo** [alejandroautalan/pygubu#277]
Hi, I am packaging the pygubu into Debian. Everything is well, but I have a debian/watch file have trouble to find upstream tag:
```
v0.9.7.7
v10.8
v10.9
```
Dose It seems that v10.8 should be v0.10.8? Because this v10.9 is here, so the latest version is v10.9 when using d/watch to detect.
Could you have a look?

**Comment by alejandroautalan** [comment]
Hello @yuzibo, thanks for trying pygubu.

I renamed the tags to:

    v10.8  > v0.10.8
    v10.9  > v0.10.9

Let me know if this helps.

Regards
Alejandro A.

**Comment by yuzibo** [comment]
hi.
I can confirm it works, thanks~
