### ISSUE TITLE
Address editabletreeview directly :enhancement:

### ISSUE THREAD

**Issue by Jorzef** [alejandroautalan/pygubu#279]
Hello a suggestion could you put a function to address put in the editabletreeview directly, I improvised by copying the __get_value function in the editabletreeview.py and giving it a name called get_value. Awesome work by the way, helps a lot designing basic UI's for scientific programs that I need. Unless I'm missing something on the way the module works this would be awesome for getting values on changed cells directly.
Saludos!

PS: Also another question I'm using this widget as a way to have an editable table with values, any way of taking the row out of focus once a click happens outside the selected row? Again thanks a lot!

**Comment by alejandroautalan** [comment]
Hello @Jorzef, thanks for trying pygubu.  I'm glad that is helpful to you.

> PS: Also another question I'm using this widget as a way to have an editable table with values, any way of taking the row out of focus once a click happens outside the selected row?

With this do you mean clicking in the white area inside the Treeview?

![Captura de pantalla de 2023-01-25 09-54-54](https://user-images.githubusercontent.com/3482471/214572340-591af30b-99a1-441f-af00-8b1342ec2d6f.png)


Regards
Alejandro A

**Comment by Jorzef** [comment]
Exactly! 😃

**Comment by Jorzef** [comment]
Just saw the commits I'll try it asap. Thanks!

**Comment by Jorzef** [comment]
Well this is perfect, thank you so much for taking the time to help me with a particular issue. I'm eternally grateful for this module as it would not be possible for me to make the programs without learning tk extensively. Thank you

**Comment by alejandroautalan** [comment]
Thanks @Jorzef  for your words 👍🏽 
Regards

Alejandro A.
