### ISSUE TITLE
The anchor property does not function when defined in xml

### ISSUE THREAD

**Issue by microbullet** [alejandroautalan/pygubu#291]
**Describe the bug**
The anchor property in xml does not function

**To Reproduce**
1. Grab the "helloworld.ui" file from the readme
2. Change the anchor property from "center" to "w" (left aligning)
3. Grab the "helloworld.py" script from the readme
4. Place both of these files in a folder together
5. Run "helloworld.py"
6. Resize the resulting window to a larger size 

**Expected behavior**
When resized the text should stay at the left of the window

**Screenshots**
![image](https://github.com/alejandroautalan/pygubu/assets/73013941/57b0e7a1-1be4-4664-b5fe-068c2b06169b)

**Your Environment (please complete the following information):**
 - OS: Windows 11
 - Python version: 3.11.7
 - Pygubu version: 0.32

**Additional context**

**Comment by alejandroautalan** [comment]
Hello @microbullet, thanks for trying pygubu.

> The anchor property in xml does not function

It is not an error, You must take into account the layout of the widget on the screen.
Look at this example and let me know if this clarifies the issue.

[2024-02-03 14-48-14.webm](https://github.com/alejandroautalan/pygubu/assets/3482471/8c54072b-6fa9-425b-bee2-3c0575fe4011)

Regards
Alejandro A.

**Comment by microbullet** [comment]
Ahhh i completely understand, thank you for clarifying!
