### ISSUE TITLE
Scrolled frame doesn't resize in grid layout

### ISSUE THREAD

**Issue by homermafia** [alejandroautalan/pygubu#293]
**Describe the bug**
I am trying to put a ScrolledFrame inside a LabelFrame and have the ScrolledFrame have a certain size different from the default one. I tried changing width, height, messing with "propagate" property, but nothing worked.
This issue was already present before and fixed, but it looks like the problem appeared again (https://github.com/alejandroautalan/pygubu/issues/50 and https://github.com/alejandroautalan/pygubu/issues/204)

**To Reproduce**
Simply create a ui file containing one of the two examples there: https://github.com/alejandroautalan/pygubu/issues/50#issuecomment-451785796
None of the two show like in the screenshot.
First example of the post -> What actually shows: 
![image](https://github.com/alejandroautalan/pygubu/assets/35042332/f0bc6487-f157-4e30-a915-22169a5cc259)
Second example of the post -> What actually shows:
![image](https://github.com/alejandroautalan/pygubu/assets/35042332/b867ee12-f6a0-4a68-a5e3-6274cd3a8839)

**Expected behavior**
First example of the post -> What should show:
![image](https://github.com/alejandroautalan/pygubu/assets/35042332/ca95961a-0cee-4bf9-8e4e-6a02c5151002)
Second example of the post -> What should show:
![image](https://github.com/alejandroautalan/pygubu/assets/35042332/439dbb5e-8a3b-4bc4-b7df-4e015af8afad)

**Screenshots**
See above.

**Your Environment (please complete the following information):**
 - OS: Windows 11
 - Python version: Python 3.8.10
 - Pygubu version: pygubu 0.33
 - Designer pygubu-designer 0.38

**Additional context**
None.

**Comment by alejandroautalan** [comment]
Hello @homermafia thanks for the report.

The examples are from a previous version, the container layout options must be adjusted.
The problem here is that the scrolledframe does not have the container layout options enabled.

I will fix it and make a new example.

Regards.
Alejandro A.

**Comment by alejandroautalan** [comment]
Fixed in pygubu v0.34.
Added example [here](https://github.com/alejandroautalan/pygubu-designer/tree/16a1611c4cc7618376e8545dea6650a3e0c0ea54/examples/scrolledframe).

Let me know if you have additional issues.

Regards
Alejandro A.

**Comment by homermafia** [comment]
Thanks, it works as I wanted now.
