### ISSUE TITLE
ValueError: unknown locale: UTF-8

### ISSUE THREAD

**Issue by dossan** [alejandroautalan/pygubu#44]
When I first run `pygubu` I had a problem saying something like this:

    ValueError: unknown locale: UTF-8

I solved it adding some lines to the `~/.bash_profile` file:

    export LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8

Yes, I am on a Mac OS X Yosemite, and I suppose you did not have the problem running it from Linux.

**Comment by alejandroautalan** [comment]
Hi,
It seems that this is a common issue with python in some OS X  versions and not caused directly by pygubu. The solution you found is the easyest and recommended.

Regards.
Alejandro A.
