### ISSUE TITLE
How to run pygubu application?

### ISSUE THREAD

**Issue by dossan** [alejandroautalan/pygubu#45]
In the `README.md` file of this repository, there's no specification on _how to run the `pygubu` application/GUI designer_. There's just an example of an application created, I suppose, with `pygubu`, and I was able to run it.

On my mac OS X, I cannot simply type `pygubu` on the terminal and the GUI designer appears (like you did in the youtube video). I had to do a painful workaround.

If I install `pygybu` using `pip3` with the following command:

    pip3 install pygubu

In my Python folder `site-packages`, I have my `pygubu` folder (and I can therefore import `pygubu` from the `IDLE`), but that folder is simply this: https://github.com/alejandroautalan/pygubu/tree/master/pygubu
Which is actually a subfolder of this repository (and not all the repository).

I couldn't run the `pygubu` designer from that folder... there was not script to run it, or something similar.

I decided to clone this whole repository, and I finally discover that under `/bin/` there's a script, which allows us to run `pygubu`.

This was very painful for me, and I hope you provide a complete guide on how to run the `pygubu` designer for various platforms, and not just for Ubuntu, where I suppose you can simply type magically `pygubu` from the terminal.

----

**Edit**:

I had noticed that I can now run `pygubu` from the terminal by simply typing `pygubu-designer` instead of simply `pygubu`...

**Comment by alejandroautalan** [comment]
Hi dossan,
Sorry for all the confusion. Since version 0.9.5 the startup script for the designer is called ***pygubu-designer*** for unix like systems. The reason is [here](https://github.com/alejandroautalan/pygubu/issues/20).
I will update the README making more clear howto run the designer (I need to update the video too).

Regards.
Alejandro A.

**Comment by lgmventura** [comment]
It still does not work. I installed it successfully through `pip3 install pygubu` and I can import it using python 3, but I can't open the designer in any way. Typing `pygubu-designer` from terminal I only get `command not found`. No script in /bin folder or anywhere else inside /usr.

Regards,
Luiz Ventura

**Comment by alejandroautalan** [comment]
Hello Luiz thanks for trying pygubu.

Installing pygubu with pip as a **normal user**, the pygubu-designer script is located at

    $HOME/.local/bin

So you can add that path to your environment variables. Or open a console, and run pygubu-designer using this command:

    ~/.local/bin/pygubu-designer

Let me know if this helps you.
Regards
Alejandro A.

**Comment by lgmventura** [comment]
Hey Alejandro, thank you very much for your attention! It worked.
Regards,
Luiz Ventura

**Comment by Robotgeek1251** [comment]
same thing happened to me, i already installed pygubu yet i cant find the designer

**Comment by Karoljv** [comment]
> Hello @Robotgeek1251, thanks for trying pygubu.
> 
> > same thing happened to me, i already installed pygubu yet i cant find the designer
> 
> The designer is now in a separate package, please install the [designer](https://github.com/alejandroautalan/pygubu-designer) with:
> 
> ```
> pip install pygubu-designer
> ```
> 
> and try again.
> 
> Regards Alejandro A.

Hi, I installed pygubu-designer via "pip install pygubu-designer" but can't locate the designer on my computer :(
