### ISSUE TITLE
No able to receive window close button event

### ISSUE THREAD

**Issue by rameshgandhim** [alejandroautalan/pygubu#49]
For Example :

def on_close():
    print ("Closed application")

root = tkinter.Tk()
root.protocol("WM_DELETE_WINDOW", on_close)
app = Application(root)
app.run()

Not sure how to catch window close event.
It will be helpful if anyone can suggest me on this.

(Big thanks for pygubu :relaxed: )

**Comment by alejandroautalan** [comment]
Hello rameshgandhim,

To close the window you need to call the destroy method in the toplevel widget.
I have just created a wiki page to show how is done.

https://github.com/alejandroautalan/pygubu/wiki/CapturingDeleteWindowEvent

Thanks for trying pygubu.
Regards.

**Comment by rameshgandhim** [comment]
Thanks alejandro!!
