### ISSUE TITLE
Pyinstaller Support

### ISSUE THREAD

**Issue by ollierexx** [alejandroautalan/pygubu#53]
Hello
I've created a GUI and while it works fine, if i attempt to build to it an exe with Pyinstaller it succeeds, but fails to import:
https://github.com/alejandroautalan/pygubu/blob/master/pygubu/builder/ttkstdwidgets.py

Screenshot:
http://puu.sh/j8fjv/95b3faf5c2.png

Any way to get it working?
Thanks

**Comment by ollierexx** [comment]
Fixed with:
from pygubu.builder import ttkstdwidgets

**Comment by alejandroautalan** [comment]
Hello, thanks for trying pygubu.
I never used pyinstaller, what file you modified to make it work?

**Comment by ollierexx** [comment]
I just added the import:
from pygubu.builder import ttkstdwidgets
to my script and it fixed the problem. 
pygubu made making the GUI much easier, thanks so much.

**Comment by alejandroautalan** [comment]
Thank you for the info.  I will test pyinstaller with pygubu later.

Regards.
Alejandro A.

**Comment by Andrej730** [comment]
Just got this error too. ghost's solution didn't helped me. What hepled is adding hidden imports in pyinstaller spec file (here is an example https://github.com/alejandroautalan/pygubu/blob/master/examples/pyinstaller/myapp.spec)

**Comment by gilmarfrancisco828** [comment]
> Fixed with:
> from pygubu.builder import ttkstdwidgets

Thanks!! it worked.
