### ISSUE TITLE
py2exe problem

### ISSUE THREAD

**Issue by strasserfj** [alejandroautalan/pygubu#54]
Hi, 
i want to use your tool in combination with py2exe. However, when i try to compile your example button_cb.py py2exe says it could not find tkinter and ElementC14N modules. 

It is possible to use py2exe with a normal tkinter or ttk application without any problem. 

I think it might be some problem with python 2.7 and 3.x compatibility. 

Steps to reproduce: 

install py2exe (http://www.py2exe.org/)
write a setup.py file 

------------------
import sys
from distutils.core import setup
import py2exe

sys.argv.append("py2exe")

setup(console=['button_cb.py'],
      data_files=[("",
                   ["button_cb.ui" # copy the ui file 
                    ])])

-----------------------------

the output of the setup script results in the message: 

------------------

The following modules appear to be missing
['ElementC14N', 'tkinter']

------------------

I am using windows 7 and my ptython version is 2.7.9

Please have a look at this issue and let me know if you need any additional information

Thanks Florian

**Comment by alejandroautalan** [comment]
Hello Florian, thanks for trying pygubu.
I installed py2exe and I got the example to work.
First I modified the button_cb.py to load the ui file when running from exe.
Then, since pygubu dynamically loads the module widgets, you need to specifiy to py2exe the extra modules to include (see setup.py bellow)
Tested on Windows XP with python 2.7.10.
If this resolves your issue please, let me know.

Regads,
Alejandro A.


```python
# button_cb.py
import sys
import os

try:
    import tkinter as tk
    from tkinter import messagebox
except:
    import Tkinter as tk
    import tkMessageBox as messagebox

try:
	CDIR = os.path.dirname(__file__)
except NameError:
	CDIR = os.path.dirname(os.path.abspath(sys.argv[0]))

import pygubu

class Myapp:
    def __init__(self, master):
        self.builder = builder = pygubu.Builder()
        fpath = os.path.join(CDIR,"button_cb.ui")
        builder.add_from_file(fpath)

        mainwindow = builder.get_object('mainwindow', master)

        builder.connect_callbacks(self)

        callbacks = {
            'on_button2_clicked': self.on_button2_clicked
            }

        builder.connect_callbacks(callbacks)

    def on_my_button_clicked(self):
        messagebox.showinfo('From callback', 'My button was clicked !!')

    def on_button2_clicked(self):
        messagebox.showinfo('From callback', 'Button 2 was clicked !!')

if __name__ == '__main__':
    root = tk.Tk()
    app = Myapp(root)
    root.mainloop()
```

```python
# setup.py
import sys
from distutils.core import setup
import py2exe

sys.argv.append("py2exe")

setup(console=["button_cb.py"],
		data_files=[("", ["button_cb.ui"])],
		options= { "py2exe": { 
                            "includes" : ["pygubu.builder.tkstdwidgets",
                                              "pygubu.builder.ttkstdwidgets",
                                              "pygubu.builder.widgets.dialog",
                                              "pygubu.builder.widgets.editabletreeview",
                                              "pygubu.builder.widgets.scrollbarhelper",
                                              "pygubu.builder.widgets.scrolledframe",
                                              "pygubu.builder.widgets.tkscrollbarhelper",
                                              "pygubu.builder.widgets.tkscrolledframe",
                                              "pygubu.builder.widgets.pathchooserinput",]
						} } ,
		)
```

**Comment by strasserfj** [comment]
Hey,

sorry for beeing late. However, thank you very much for your fast and 
qualified answer! I will use it as soon as possible in my company.

Yours Florian

Am 24/07/15 um 10:17 schrieb Alejandro Autalán:
>
> Hello Florian, thanks for trying pygubu.
> I installed py2exe and I got the example to work.
> First I modified the button_cb.py to load the ui file when running 
> from exe.
> Then, since pygubu dynamically loads the module widgets, you need to 
> specifiy to py2exe the extra modules to include (see setup.py bellow)
> Tested on Windows XP with python 2.7.10.
> If this resolves your issue please, let me know.
>
> Regads,
> Alejandro A.
>
> # button_cb.py
> import  sys
> import  os
>
> try:
>      import  tkinteras  tk
>      from  tkinterimport  messagebox
> except:
>      import  Tkinteras  tk
>      import  tkMessageBoxas  messagebox
>
> try:
>      CDIR=  os.path.dirname(__file__)
> except  NameError:
>      CDIR=  os.path.dirname(os.path.abspath(sys.argv[0]))
>
> import  pygubu
>
> class  Myapp:
>      def  __init__(self,master):
>          self.builder=  builder=  pygubu.Builder()
>          fpath=  os.path.join(CDIR,"button_cb.ui")
>          builder.add_from_file(fpath)
>
>          mainwindow=  builder.get_object('mainwindow', master)
>
>          builder.connect_callbacks(self)
>
>          callbacks=  {
>              'on_button2_clicked':self.on_button2_clicked
>              }
>
>          builder.connect_callbacks(callbacks)
>
>      def  on_my_button_clicked(self):
>          messagebox.showinfo(' From callback','My button was clicked !!')
>
>      def  on_button2_clicked(self):
>          messagebox.showinfo(' From callback','Button 2 was clicked !!')
>
> if  __name__  ==  '__main__':
>      root=  tk.Tk()
>      app=  Myapp(root)
>      root.mainloop()
> # setup.py
> import  sys
> from  distutils.coreimport  setup
> import  py2exe
>
> sys.argv.append("py2exe")
>
> setup(console=["button_cb.py"],
>          data_files=[("", ["button_cb.ui"])],
>          options=  {"py2exe": {
>                              "includes"  : ["pygubu.builder.tkstdwidgets",
>                                                "pygubu.builder.ttkstdwidgets",
>                                                "pygubu.builder.widgets.dialog",
>                                                "pygubu.builder.widgets.editabletreeview",
>                                                "pygubu.builder.widgets.scrollbarhelper",
>                                                "pygubu.builder.widgets.scrolledframe",
>                                                "pygubu.builder.widgets.tkscrollbarhelper",
>                                                "pygubu.builder.widgets.tkscrolledframe",
>                                                "pygubu.builder.widgets.pathchooserinput",]
>                          } } ,
>          )
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/alejandroautalan/pygubu/issues/54#issuecomment-124428763>.
>

Mit freundlichen Grüßen
     Strasser Florian

-- 
---------------------------------------------------
| Strasser Florian
| Android Developer
| Dipl. Ing. Telematik
| strasserfj@gmail.com
---------------------------------------------------
