### ISSUE TITLE
Problem compiling stand-alone with nuitka cross compiler

### ISSUE THREAD

**Issue by tcareyintx** [alejandroautalan/pygubu#62]
Hello,

I was trying to compile my python program using Nuitka cross platform compiler.

The compile worked but it threw the following errors and when I hit the executable it fails to load the window.
Version of Nuitka 0.5,15
Python 3.4

The command execution I use is: nuitka --mingw --standalone --remove-output

Has pygubu been compiled as a standalone, If so with which products

Nuitka:WARNING:C:\Python34\Lib\site-packages\pygubu\widgets\pathchooserinput.py:8: Cannot find 'Tkinter' in package 'pygubu.widgets' as absolute import.
Nuitka:WARNING:C:\Python34\Lib\site-packages\pygubu\widgets\pathchooserinput.py:9: Cannot find 'ttk' in package 'pygubu.widgets' as absolute import.
Nuitka:WARNING:C:\Python34\Lib\site-packages\pygubu\widgets\pathchooserinput.py:10: Cannot find 'tkFileDialog' in package 'pygubu.widgets' as absolute import.
Nuitka:WARNING:C:\Python34\Lib\site-packages\pygubu\builder\__init__.py:28: Cannot find 'Tkinter' in package 'pygubu.builder' as absolute import.
Nuitka:WARNING:C:\Python34\Lib\site-packages\pygubu\stockimage.py:27: Cannot find 'Tkinter' in package 'pygubu' as absolute import.

**Comment by alejandroautalan** [comment]
Hello, thanks for trying pygubu.

Pygubu can be used with no problems with py2exe and cx_freeze. See this examples:
https://github.com/alejandroautalan/pygubu/tree/master/examples/cx_freeze
https://github.com/alejandroautalan/pygubu/tree/master/examples/py2exe

I never used nuitka, but I'll take a look to see what may be the problem.

Regards
Alejandro A.

**Comment by tcareyintx** [comment]
Thanks
I get these compile warnings and then when I execute the application I receive.
I removed the warnings from the compiler by editting out the try/except to see if that would help.
It removed the warnings but I still get traceback:
Traceback (most recent call last):
  File "C:\Users\tcarey\ntemp\report_application.dist\report_application.py", line 2810, in <module>
  File "C:\Users\tcarey\ntemp\report_application.dist\report_application.py", line 2804, in main
  File "C:\Users\tcarey\ntemp\report_application.dist\report_application.py", line 1693, in __init__
  File "C:\Users\tcarey\ntemp\report_application.dist\pygubu\__init__.py", line 25, in __init__
  File "C:\Users\tcarey\ntemp\report_application.dist\report_application.py", line 1921, in _create_ui
  File "C:\Users\tcarey\ntemp\report_application.dist\pygubu\builder\__init__.py", line 326, in get_object
  File "C:\Users\tcarey\ntemp\report_application.dist\pygubu\builder\__init__.py", line 359, in _realize
  File "C:\Users\tcarey\ntemp\report_application.dist\pygubu\builder\__init__.py", line 334, in _import_class
  File "C:\Python34\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'pygubu.builder.ttkstdwidgets'

**Comment by alejandroautalan** [comment]
Hi Tim

Sorry for the late response. To include pygubu on the final executable, you need to specify the installation path of the module using the "--recurse-directory" option.

For example, to compile the button_cb.py example I did the following steps.

```
cd c:\tmp\nuitkatest

c:\tmp\nuitkatest> python --version
Python 3.5.0

c:\tmp\nuitkatest> nuitka --version
0.5.16

c:\tmp\nuitkatest> dir 
button_cb.ui
button_cb.py

c:\tmp\nuitkatest> nuitka --recurse-all --recurse-directory=c:\Python35\Lib\dist-packages/pygubu --show-progress --standalone button_cb.py
```

Move data (*.ui files, images, etc.) files to dist directory.

```
c:\tmp\nuitkatest> copy button_cb.ui button_cb.dist
```

Then run the executable in the dist option. No error shown.

Regards
Alejandro A.

**Comment by deajan** [comment]
Sorry to add my 2 cents to this already closed bug.

Using pygubu with nuitka works flawlessly unless using ttk widgets instead of tk widgets.
Using your solution to recurse into pygubu lib makes compilation work, but execution fails just after loading tkinter.ttk.

Any clues why nuitka can't automatically resolve ttk dependancy 
Thanks.

**Comment by alejandroautalan** [comment]
Hello deajan, thanks for trying pygubu and sorry for the late response.

I was investigating your problem and found the following.

* The "recurse-directory" option is not enough. Pygubu imports ttk modules dynamically and nuitka is not smart enough to include the required files.
* I could not find a way to force the inclusion of a file in nuitka's compilation process. However, by explicitly importing the pygubu modules, it is possible to compile the application.
* I had no problems importing the tkinter.ttk module

I managed to compile a simple example using ttk widgets. You can find it here https://github.com/alejandroautalan/pygubu/tree/master/examples/nuitka

If this helps you, let me know.

Regards.
Alejandro A.

**Comment by deajan** [comment]
Hello Alejandro,

Thanks for your help.
Indeed using the nuitkahelper.py works for compilation.
My app (and your test app btw) compiles, but still stops responding when launched.
I think at this point there must be a problem with my toolchain or nuitka.

Anyway, big thanks for the nuitkahelper.py file, it makes things pretty straitforward.
And REALLY big thanks for pygubu, makes life lot easier :)

Regards,
Ozy.

**Comment by deajan** [comment]
Just for the info, it was indeed my toolchain bugging around (using mingw64 instead of microsoft compiler).

Thanks for everything.

**Comment by alejandroautalan** [comment]
Hi Orsiris, thanks for the info!

Regards
Alejandro A.
