### ISSUE TITLE
Listbox and Scrollbar

### ISSUE THREAD

**Issue by mkli90** [alejandroautalan/pygubu#63]
Hi,
first of all nice work with pygubu. I've been using it for several projects now, since the usability is very intuitive! However I came across a problem I can't figure out. I added a Listbox and a Scrollbar via pygubu and set the scrollbar with the listbox according to this:
http://effbot.org/tkinterbook/listbox.htm (Just look for "scrollbar")
So in pygubu I set the yscrollcommand for the Listbox to scrollbar.set, while setting the command of scrollbar to listbox.yview. When doing this I'm getting a:

_WARNING:pygubu.builder:Missing callbacks for commands: ['command_box.yview', 'scrollbar.set']_

I tried #30, but in the example you share you do setup a scrollbar but not tell it to interact with the listbox (or am I missing sth here?). See this screenshot as an example:

![scrollbar_listbox](https://cloud.githubusercontent.com/assets/8678523/11169660/cfb6998c-8bbd-11e5-91de-e2f3744329cf.png)

Is this a bug, or am I doing sth wrong? Thanks in advance

Cheers Max

**Comment by alejandroautalan** [comment]
Hello Max, thanks for trying pygubu.

Pygubu designer expects __command properties__ (such as *command*, *xscrollcommand*, *yscrollcommand*, etc.) to be function names that you must define in your code and then connect them using the builder method __connect_callbacks__.
See https://github.com/alejandroautalan/pygubu/wiki/CommandProperties

Currently you can not put an expression like "command_box.yview" in a command property. But you can propose this as a new feature :)

What I wanted to show in #30 is that it is possible to obtain the tk widgets and configure them in code.
For example, to connect a Listbox and a Scrollbar named "command_box" and "scrollbar" respectively:

```python
# Create the widget using a master as parent
self.mainwindow = builder.get_object('mainwindow', master)
# ...
listbox = builder.get_object('command_box')
scrollbar = builder.get_object('scrollbar')
listbox.configure(yscrollcommand=scrollbar.set)
scrollbar.configure(command=listbox.yview)
# ...
```

Also, for simple scrollbars, you can use a __Scrollbarhelper__ widget (pygubu.builder.widget.scrollbarhelper) that adds scrollbars to any widget that support the xscrollcommand and yscrollcommand commands (It is in the 'Pygubu Helpers' section in the Widget List). In your example, put a *Scrollbarhelper* widget and inside it, a Listbox.

I hope this helps you. Let me know.
Regards
Alejandro A.

**Comment by mkli90** [comment]
> In your example, put a Scrollbarhelper widget and inside it, a Listbox. A Scrollbarhelper is used in #30 to automatically add scrollbars to the Listbox.

Man, awesome! This works like a charm. For now I'll use that and propose the feature as soon as I got some free time. Maybe I'll also implement it and send you the PR. Thanks for the quick response

:+1: :+1: :+1:

For future reference, here's a small demo to illustrate how to get a listbox with a hooked-up scrollbar:

https://www.mklingmann.com/files/webm/listbox.webm

Cheers Max
