### ISSUE TITLE
Installing doesn't work with newer pip

### ISSUE THREAD

**Issue by Ivoz** [alejandroautalan/pygubu#65]
Hi there, I tried to install pygubu with pip. I am using Anaconda-distributed Python 3.5 on Windows 7 x86.

After installing succesfully, I get this when trying to run the script installed:

```
[sanatize] C:\Users\Staff>pygubu-designer

[sanatize] C:\Users\Staff>C:\Miniconda3\envs\sanatize\python.exe build\bdist.win
32\wheel\pygubu-0.9.7.7.data\scripts\pygubu-designer.py
C:\Miniconda3\envs\sanatize\python.exe: can't open file 'build\bdist.win32\wheel
\pygubu-0.9.7.7.data\scripts\pygubu-designer.py': [Errno 2] No such file or dire
ctory
```

This might be because of pip's new behaviour to create a wheel from all packages and install the wheel, by default.

For now, issuing `pip install --no-binary pygubu pygubu` works, but you might want to fix the default behaviour to work with when pygubu is packaged as a wheel.

**Comment by alejandroautalan** [comment]
Hi Ivoz, thanks for trying pygubu.

I will try to reproduce your issue and fix pygubu to work as a wheel.

Regards.
Alejandro A.

**Comment by Ivoz** [comment]
Incase you'd like any extra information on 'modern python packaging' (incase that's confusing, I know it can be for anything complicated), then the best guide is here currently:

https://packaging.python.org/en/latest/distributing/

If there is anything in that guide which you have a question for but isn't answered, feel free to ask for an answer on the [guide's issue tracker](https://github.com/pypa/python-packaging-user-guide)

**Comment by Ivoz** [comment]
@alejandroautalan have you tried using the [`entry_points`](https://packaging.python.org/en/latest/distributing/#entry-points) field for installing a startup script with setuptools? I highly recommend you do, if you haven't yet so far. It generates a proper .exe and everything on Windows.

Otherwise, thanks for fixing :+1:

**Comment by alejandroautalan** [comment]
Hi Ivoz,
I will investigate more about entry_points and implement that on pygubu.
Thanks for your comments.

Regards.
Alejandro a.
