### ISSUE TITLE
capturing other events

### ISSUE THREAD

**Issue by VinceLewis** [alejandroautalan/pygubu#68]
Hi. I'm familiar with Python, just getting started with Tkinter, found your gui designer, nice idea. I can see how things like buttons work, but how do I test for other events?

For example - 
how do I code for when an Entry gets or loses the focus? Or for when someone presses Enter in and Entry box?
how do I get the mouse position and which button is clicked?

Are these catered for? Do you have any examples?

**Comment by alejandroautalan** [comment]
Hello Vince, thanks for trying pygubu and sorry for the late response.

In code, you can do whatever tkinter allows to do once you have the widget instance.
To get a widget instance from the pygubu builder, you use the ```get_object``` method.

For example, suppose you have a canvas widget named 'canvas1' and you want to react whenever the user clicks the left mouse button.
To implement this behavior in code we can write:

```python
canvas = builder.get_object('canvas1')
canvas.bind('<Button-1>', on_leftbtn_clicked)
```

To reduce code typing, the pygubu-designer allows you to define the events and event handlers in the "Bindings" section for each widget.
Next you code the event handlers and connect them using the builder method ```connect_callbacks```.

I made a video showing some of the examples you requested (no audio, sorry). https://youtu.be/9p5ebkmWPr0

The wiki has some useful tips also https://github.com/alejandroautalan/pygubu/wiki.



Regards
Alejandro A.

**Comment by VinceLewis** [comment]
Many thanks for your reply, I'll have a go this week.
Vince
