### ISSUE TITLE
pygubudesigner can't open ui file

### ISSUE THREAD

**Issue by RFVenter** [alejandroautalan/pygubu#70]
I can open the pygubu designer, but when I atempt to open a saved ui xml fle then this ir what I get on the command prompt.

C:\Python27\Scripts>c:\python27\python.exe -m pygubudesigner
python version: 2.7.12 on win32
pygubu version: 0.9.7.8
Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\python27\lib\lib-tk\Tkinter.py", line 1537, in **call**
    return self.func(_args)
  File "c:\python27\lib\site-packages\pygubu\builder\tkstdwidgets.py", line 489, in item_callback
    callback(item_id)
  File "c:\python27\lib\site-packages\pygubudesigner\main.py", line 441, in on_file_menuitem_clicked
    fname = filedialog.askopenfilename(_*options)
AttributeError: 'module' object has no attribute 'askopenfilename'

**Comment by RFVenter** [comment]
It seems like I have tkinter and Tkinter on my system. the tkinter version does not have tkinter.filedialog.askopenfilename
I commented out these lines in the C:\Python27\Lib\site-packages\pygubudesigner\main.py file

from __future__ import unicode_literals
import os
import sys
import logging
import webbrowser
import importlib

# try:
#     import tkinter as tk
#     from tkinter import ttk
#     from tkinter import filedialog
#     from tkinter import messagebox
# except:
import Tkinter as tk
import ttk
import tkMessageBox as messagebox
import tkFileDialog as filedialog

**Comment by alejandroautalan** [comment]
Hello Ryan, thanks for trying pygubu.

I did a fresh install of python 2.7.12 and  pip install pygubu, and I can't reproduce the issue.
What is the other python version that you have installed?
May be there is a file named tkinter.py in your project directory?

Regards.
Alejandro A.

**Comment by RFVenter** [comment]
Hi there. Thakn you for creating awesome usefull software, and sharing. OK, after python 2.7 install I did a pip install tkinter, so now I do have Tkinter and tkinter on python 2.7. It seems that the tkinter on 2.7 does not have tkinter.filedialog.askopenfilename. After commenting out the lines above I ensured that python loads the correct version of Tkinter on python 2,7

**Comment by jawad427** [comment]
Hi plz tell me how to open pygubu it is installed and can be seen in pip list .. but i cant find any pygubu.exe file

**Comment by alejandroautalan** [comment]
> Hi plz tell me how to open pygubu it is installed and can be seen in pip list .. but i cant find any pygubu.exe file

Hello. To use the designer you need to install pygubu-designer. Since version 0.10 the project was splitted in two parts, see the README file.

What OS are you using ?

Regards
Alejandro A.
