### ISSUE TITLE
Wiki Usage Page: pathchooserinput

### ISSUE THREAD

**Issue by maryamdev** [alejandroautalan/pygubu#71]
Hello, Alejandro!

Thanks for your great efforts!

Could you please write a Wiki "Usage Page" for pathchooserinput

I could not get how to retrieve the file path selected by the user to be able to open it later.

Your other Usage Page articles are really helpful.

Many thanks in advance!

**Comment by alejandroautalan** [comment]
Hi maryamdev, thanks for trying pygubu!

I wrote a short description for the PathChooserInput widget [here](https://github.com/alejandroautalan/pygubu/wiki/PathChooserInput).
Sorry for the late reply, If you have other questions do not hesitate to consult.

Regards!
Alejandro A.

**Comment by maryamdev** [comment]
Many thanks, Alejandro! Highly appreciated!
