### ISSUE TITLE
EditableTreeView - focus question

### ISSUE THREAD

**Issue by tcareynokia** [alejandroautalan/pygubu#74]
Hi,

I am using the EditableTreeView with multiple columns in the heading style. 
I am finding that when I select on another field other than the inplace fields (e.g., just another text field on the window) the last select inplace row remains selected.

I don't have an issue per say that the row remains sellected per se except if I try to resize the columns - only the header an unselected rows are resized - not the selected row.

Any help would be appreciated.

**Comment by alejandroautalan** [comment]
Hello,
I see the problem. I will try to fix it as soon as posible.

But, in the mean time here is a quick hack:

Assuming that **etv** is an EditableTreeview instance, add a binding:
```python
class MyApplication(object):
    def __init__(self, master):
        # ....
        self.etv.bind('<ButtonRelease>', self.on_btn_release)

    def on_btn_release(self, event):
        r = event.widget.identify_region(event.x, event.y)
        if r in ('separator', 'header'):
            event.widget.event_generate('<Configure>')
```
This will resize the editor widgets also.

Regards.
Alejandro A.
