### ISSUE TITLE
Get widget_id from event

### ISSUE THREAD

**Issue by DjVw321** [alejandroautalan/pygubu#75]
Hello Alejandro,

I was wondering if there is a way to get the widget_id of an object from the event handler?

I have a button that is bound to an event. When this button is clicked, I have it run a small callback. I would like to have it add the widget_id of the button to a list. Is this possible, or should I be doing this some other way?

**Comment by alejandroautalan** [comment]
Hi DjVw321,

> I was wondering if there is a way to get the widget_id of an object from the event handler?

At present, If you set event handler from the gui-designer using the ***command*** property of the button, you don't have this info :(.

Menu commands have a custom property called ***command_id_arg*** that when is true, the widget_id is passed to the event handler see [MenuTipsAndTricks](https://github.com/alejandroautalan/pygubu/wiki/MenuTipsAndTricks).
If you think that it will be useful, I can implement this funcionality for buttons on a next release.

For now you can only do it manually, by setting the event handler of the button in code.

Let me know.

Regards
Alejandro A.

**Comment by DjVw321** [comment]
I don't think it is entirely necessary. It took me a little bit of experimentation, but I figured out how to do what I needed to do. Thank you for the reply, though!

**Comment by lalo-uy** [comment]
First thanks to Alejandro for a nice tool.
I think it is very useful, if you have several buttons that call the same function.
Pleas DjVw321 show here how you made it.
