### ISSUE TITLE
The pygubu-designer.bat is not executing

### ISSUE THREAD

**Issue by AbdelrahmanHossam** [alejandroautalan/pygubu#76]
i have successfully installed and imported pygubu but when i click on the bat file it doesn't execute, i am using anaconda python 3.5.2

**Comment by alejandroautalan** [comment]
Hello AbdelrahmanHossam, thanks for trying pygubu and sorry for the late response.

Can you run the bat file from the console and show me the program output?

Regards.
Alejandro A.

**Comment by alejandroautalan** [comment]
Hi,
I installed anaconda 4.2.0 with python 3.5.2
I Installed pygubu from the anaconda command prompt using:  pip install pygubu
I ran the pygubu-designer.bat file and the program runs normally without errors.
Tested in windows 7 32 bits.

Please give me more info about your problem.
Regards.
Alejandro A.

**Comment by jump3r34** [comment]
Alejandro - what's your path install location of the .bat file and where is your Python.exe at?  Also is your Python executable in your env variables path?

If you give me those three things I can give you command line arg that will run the bat file.
