### ISSUE TITLE
I have question about how to close the App

### ISSUE THREAD

**Issue by green-dalii** [alejandroautalan/pygubu#77]
Hello,thank your pygubu for helping me save time.
I have a question that when I run my App in Python Console,and click the X button right coner in Windows to close the App,the UI has closed,but the App is still running in the Python Console,Whta's wrong?

**Comment by alejandroautalan** [comment]
Hello green-dalii, thanks for trying pygubu and sorry for the late response.

Maybe you are not destroying the top level window correctly.
See this https://github.com/alejandroautalan/pygubu/wiki/CapturingDeleteWindowEvent  and let me know if this solves your problem.

Regards
Alejandro A.

**Comment by green-dalii** [comment]
Thank you.
I have solved the problem.
