### ISSUE TITLE
The problem about packing into exe.

### ISSUE THREAD

**Issue by green-dalii** [alejandroautalan/pygubu#78]
Thank you a lot for your project.I have another problem using PyInstaller to pack my pygubu script to executable file in Windows.
When I only use Tkinker and ttk,all is OK,the transformed exe file runs correctly. When I use pygubu to define UI,running from Python script is ok too,while use PyInstaller to pack,the executable file can't run.
Is there something wrong that imported pygubu module not recognized by PyInstaller?

**Comment by alejandroautalan** [comment]
Hi green-dalii,

I never used PyInstaller, but the main issue is to find in the documentation howto tell PyInstaller to include extra modules (pygubu modules).

Here are some examples of using other application freezing systems and pygubu. Maybe they can guide you somehow:
    https://github.com/alejandroautalan/pygubu/tree/master/examples/py2exe
    https://github.com/alejandroautalan/pygubu/tree/master/examples/cx_freeze
    https://github.com/alejandroautalan/pygubu/tree/master/examples/nuitka

Anyway, when I have a free moment I will try PyInstaller and create an example.

Regards.
Alejandro A.

**Comment by jawad427** [comment]
Hi i cant find pygubu.exe file anywhere ..its installed .. showing in piplist
