### ISSUE TITLE
'pygubu-designer.bat' fails to execute

### ISSUE THREAD

**Issue by tscv13** [alejandroautalan/pygubu#79]
I use Windows 10 Pro x64, a Dell Inspiron 5000 series laptop, and python 2.7.12. I am also a developer
 (python, amateur), and I'm very interested in using pygubu. It worked for me at one point - I even
 successfully imported and used a custom widget, but when I came back to it another time the .bat would
 not execute again (that's also what happened in the beginning, before I finally got it to run - unfortunately
 I'm not sure what did the trick when it did work). I have time if you need to know more about the problem.
 I would like to solve it and begin using your (excellent) program again!

**Comment by tscv13** [comment]
I just remembered to get the command window output when attempting to install - it appears I'm missing module: 'customappwidgets'. If I recall that was something I tried from your examples somewhere. I did create a simple test gui and it worked perfectly, and as I mentioned a custom widget was imported and used as well. I still have most of those files but no 'customappwidgets' in the project folder, no mention of 'customappwidgets' when I search my entire hard drive with Everything Search. I have uninstalled and reinstalled pygubu "successfully" again and still have a .bat that doesn't run. Hopefully you will enlighten me! Thanks for your time.

**Comment by tscv13** [comment]
I just remembered to get the command window output when attempting to install - it appears I'm missing module: 'customappwidgets'. If I recall that was something I tried from your examples somewhere. I did create a simple test gui and it worked perfectly, and as I mentioned a custom widget was imported and used as well. I still have most of those files but no 'customappwidgets' in the project folder, no mention of 'customappwidgets' when I search my entire hard drive with Everything Search. I have uninstalled and reinstalled pygubu "successfully" again and still have a .bat that doesn't run. Hopefully you will enlighten me! Thanks for your time.

**Comment by tscv13** [comment]
I resolved this by 'grep-ping' my way through all folders with 'pygubu' in their names until I found the 'config' file in 'C:\Users\TC\AppData\Local\pygubu-designer' and removed the line containing 'customappwidgets.' I should have spent more time on it before bothering you, but thanks anyway!

**Comment by alejandroautalan** [comment]
Hi tscv13. Thanks for trying pygubu and sorry for the late response.

I'm glad you solved the problem.
I'm going to put a check or alert message when custom widget fails to load.

Thank you for your contribution. Do not hesitate to consult when you have a problem.

Regards.
Alejandro A.
