### ISSUE TITLE
PAGE - Python Automatic GUI Generator - for Tcl/Tk and Python

### ISSUE THREAD

**Issue by ghost** [alejandroautalan/pygubu#82]
Are you aware of PAGE?

The best thing feature is the boiler plate code in Python it creates.

http://page.sourceforge.net/

**Comment by alejandroautalan** [comment]
Hello eno93, thanks for trying pygubu.

I heard about the project page, but I never used it.
Do you mean to add an option similar to "Generate support module" to pygubu?
Can you explain a little more your request? Some other ideas have been proposed in issue #29.

Regards
Alejandro A.

**Comment by KMFSousa** [comment]
I'm going to further explain. PAGE is a GUI Generator similar to yours here. From a very quick trial of both the two benefits (one as suggested in #29 ) it has over pygubu is that it is drag and drop and that it will generate the .py file for all your GUI's code which you can than go ahead and edit further and incorporate  into already built projects.

**Comment by oldmud0** [comment]
PAGE is all written in Tcl. The UI generator is, by itself, 4,300 lines of Tcl. I'd rather have a Python generator be written in Python, in case something breaks..

**Comment by AllenGovender** [comment]
Hi , I just downloaded Page version 4.9. When I try to run the program it comes up with 'Windows cannot find wish.exe' Any ideas?

**Comment by AllenGovender** [comment]
Sorted. Had to install TCL

**Comment by insolor** [comment]
@AllenGovender this is unrelated to Pygubu anyway

**Comment by Xonem1** [comment]
Where is the code? i only see the .exe and i dont have admin rights

**Comment by b20darryll** [comment]
How to fix "No Output"

**Comment by vipinoceans** [comment]
Any idea how to install page on mac os?

**Comment by MohamedRaafat188** [comment]
please I downloaded and installed page 6.0.1 and activestate but it doesn't work it's not even open the app

**Comment by insolor** [comment]
@MohamedRaafat188 PAGE not related to PyGubu in any way.

**Comment by insolor** [comment]
@alejandroautalan I think it makes sense to close this issue

**Comment by mahesh-imj** [comment]
Is ActivePython must for running PAGE??

**Comment by insolor** [comment]
@mahesh-imj this is an issue created on the pygubu project. As I said before, PAGE is not related to pygubu. I don't think it makes sense to ask questions about PAGE here.

**Comment by QGB** [comment]
Python GUI Generator: PAGE
