### ISSUE TITLE
bash: pygubu-designer: command not found

### ISSUE THREAD

**Issue by GildedHonour** [alejandroautalan/pygubu#84]
Having installed it via pip3.5 on Linux, the command "pygubu-designer" returns an error:

    bash: pygubu-designer: command not found

although "import pygubu" in REPL works well.

**Comment by alejandroautalan** [comment]
Hello. Thanks for trying pygubu.
Please try the latest version and let me know if it was fixed.

Regards.
Alejandro A.

**Comment by mithat** [comment]
Please reopen: I had the exact same experience as @GildedHonour.

Searching for `pygubu-designer` revealed it in `$HOME/.local/bin`, which is not on the PATH in Debian systems. AFAIK, `$HOME/bin` is more of a standard than `$HOME/.local/bin` for user executables.

My workaround was to add a symbolic link to `$HOME/bin`.

**Comment by alejandroautalan** [comment]
Hello mithat, thanks for trying pygubu.

Can you post the install command that you are using?
Are you installing using a normal user or admin user?
Debian version ?

Regards.
Alejandro A.

**Comment by mithat** [comment]
I installed as user:
```
pip3 install pygubu
```
I'm on 64-bit Debian sid, Python 3.5.3.
```
$ pygubu-designer
python version: 3.5.3 on linux
pygubu version: 0.9.8.1
```

**Comment by alejandroautalan** [comment]
Hi mithat, thanks for the info.
I think it is not a problem of pygubu but of pip and its method of installation as normal user.
Pip already has an open bug on this topic, see here: https://github.com/pypa/pip/issues/3813
For now I recommend that you continue using your workaround or add $HOME/.local/bin to the $PATH variable in your bash profile.

Regards
Alejandro A.

**Comment by swimchiu** [comment]
Hi , I have the same issue on MacOS 10.15 , here is the installing log and error message:

% pip3 install pygubu
Collecting pygubu
  Downloading pygubu-0.10.2-py3-none-any.whl (59 kB)
     |████████████████████████████████| 59 kB 89 kB/s 
Installing collected packages: pygubu
Successfully installed pygubu-0.10.2

% pygubu
zsh: command not found: pygubu

I have checked the install path of pygubu:
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pygubu

**Comment by mikegrep** [comment]
Same here on Ubuntu 18.04 
pc@pc-pc:~/instagramBot/bot_lates/tv_mount_gui$ pip3 install pygubu
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pygubu in /home/pc/.local/lib/python3.6/site-packages (0.10.3)

bash: pygubu: command not found

**Comment by alejandroautalan** [comment]
> Same here on Ubuntu 18.04
> pc@pc-pc:~/tv_mount_gui$ pip3 install pygubu
> Defaulting to user installation because normal site-packages is not writeable
> Requirement already satisfied: pygubu in /home/pc/.local/lib/python3.6/site-packages (0.10.3)
> 
> bash: pygubu: command not found

Hi mikegrep, thanks for trying pygubu.

As described in the readme, the project was divided into two modules: pygubu and pygubu-designer.
To install the designer, run:

    pip install pygubu-designer

Then for running it:

    pygubu-designer

Regards
Alejandro A.
