### ISSUE TITLE
Cannot add file definition to current tree

### ISSUE THREAD

**Issue by keplerk** [alejandroautalan/pygubu#87]
As the title says i cannot add a new file to a current tree and i think i found the problem

![image](https://cloud.githubusercontent.com/assets/4659797/21503535/1ecf858e-cc0d-11e6-9607-e67637ac9135.png)

Any plans to change it ?

**Comment by alejandroautalan** [comment]
Hello keplerk, thanks for trying pygubu.

Yes that functionality is not completed yet. I will try to complete it for version 1.0.
For now, you can use a builder object for each .ui file you have.

Regards.
Alejandro A.

**Comment by keplerk** [comment]
Thanks, but because I'm a little bit impatient jeje I found a way to achieve that, I even create a method to just input a directory and it will automatically load all the ui files, there was a issue with the command assignation but i solved it already.

Meanwhile officially you release those features I will use my workaround.

Regards.
Armando L.
