### ISSUE TITLE
Cannot open Pygubu from Terminal

### ISSUE THREAD

**Issue by alauit** [alejandroautalan/pygubu#96]
Hi

I am using MacOS and cannot seem to open Pygubu designer from the Tutorial using the 
`pygubu-designer` command.

I get an error that reads:
 `pkg_resources.DistributionNotFound: The 'appdirs>=1.3' distribution was not found and is required by pygubu`

![screen shot 2017-03-01 at 00 34 33](https://cloud.githubusercontent.com/assets/26100639/23440873/d9d43bdc-fe16-11e6-98c5-9b9631121442.jpg)

Many Thanks in Advance

**Comment by alejandroautalan** [comment]
Hello alauit, thanks for trying pygubu, and sorry for the late response.

Pygubu uses appdir package.  Please install it using pip or your corresponding OS package manager (I don´t have access to a mac).
Example:
```
pip install appdirs
```

Let me know if that works. Regards.
Alejandro A.
