### ISSUE TITLE
Sorry ;/

### ISSUE THREAD

**Issue by alauit** [alejandroautalan/pygubu#98]
Sorry for asking so many questions, pygubu is great and i am trying to use it for my assesment project

Is there any way pygubu can run natively? (ie. install pygubu files in the same folder as py so it can be run on a machine which does not have pygubu setup)

Is there a way to save/convert the .ui file into a .py file? like PyQt

Many thanks

**Comment by alejandroautalan** [comment]
Hi alauit

> Sorry for asking so many questions, pygubu is great and i am trying to use it for my assesment project

Do not worry, you can ask the questions you want.

> Is there any way pygubu can run natively? (ie. install pygubu files in the same folder as py so it can be run on a machine which does not have pygubu setup)

I did not try that.  Maybe you can use some freezing applications like cx-freeze (or nuitka, pyinstaller, py2exe). There is a litle example  here https://github.com/alejandroautalan/pygubu/tree/master/examples/cx_freeze

> Is there a way to save/convert the .ui file into a .py file? like PyQt

No, not for the moment.

Best regards.
Alejandro A.
